### ISSUE TITLE
Observation: vSphere HA is disabled, DRS enabled with policy based PV provisioning

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#120]
When` kubernetes-helper-vm` is in the "disconnected state", PVC creation is failing with " A general system error occurred: Invalid fault".

This can happen when vSphere HA is disabled.

```
$ kubectl create -f vsan_pvc_02.yaml 
persistentvolumeclaim "policyclaim02" created

$ kubectl describe pvc policyclaim02
Name:		policyclaim02
Namespace:	default
StorageClass:	vsansc
Status:		Bound
Volume:		pvc-9e807cde-1322-11e7-9ab0-005056bd8adc
Labels:		<none>
Capacity:	2Gi
Access Modes:	RWO
Events:
  FirstSeen	LastSeen	Count	From				SubObjectPath	Type		Reason			Message
  ---------	--------	-----	----				-------------	--------	------			-------
  23m		3m		78	{persistentvolume-controller }			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "vsansc": ServerFaultCode: A general system error occurred: Invalid fault
  3m		1m		7	{persistentvolume-controller }			Warning		ProvisioningFailed	Failed to provision volume with StorageClass "vsansc": Unable to communicate with the remote host, since it is disconnected.
```
 Eventually when kubernetes-helper-vm is conencted back, PV is provisioned after 85 failed attempt.

**Creating issue for documenting recommendation of vSphere HA for Policy based Volume Provisioning.** 

 @BaluDontu @tusharnt

**Comment by divyenpatel** [comment]
Fault for Reference:

 -- vim.VirtualMachine.reconfigure: vmodl.fault.HostNotConnected:
--> Result:
--> (vmodl.fault.HostNotConnected) {
-->    faultCause = (vmodl.MethodFault) null, 
-->    faultMessage = <unset>
-->    msg = ""
--> }

**Comment by BaluDontu** [comment]
If vSphere HA is enables then we would not run into this issue as the dummy VM which is now in a disconnected state will be provisioned on other ESX host. 

Btw, dummyVM went into a disconnected state as the ESX host went down. There seems to be no other option on the VC UI to vMotion, provision on other ESX host. 

However we must have a way to tackle this issue. I will think about it and come up with a solution.

As a workaround, user might have 2 options.
1. Enable vSphere HA.
2. Remove ESX host that went down. This will remove the dummyVM from inventory. Now in this case, when the user creates a PVC a new dummyVM will be created and will be able to process any incoming requests. When the user resolves the issue on ESX host he might add the host back onto VC. However, all the VM's can now be added to main cluster resource pool (or) under a new resource pool. So this dummyVM which is initially a part of disconnected ESX host will now be added back to main resource pool. This will not effect the dummyVM which is already running under kubernetes cluster resource pool. The downside is user see 2 dummyVM instances on the inventory, and the user can go ahead and remove the dummyVM which is part of main cluster resource pool from the inventory.

**Comment by divyenpatel** [comment]
Implementation has changed. We do recommend user to enable vSphere HA.
closing this issue.
