### ISSUE TITLE
Tag a release for kuberenetes-anywhere

### ISSUE THREAD

**Issue by tusharnt** [vmware/kubernetes#125]
Tag a release for kuberenetes-anywhere.

**Comment by abrarshivani** [comment]
Created issue here: https://github.com/kubernetes/kubernetes-anywhere/issues/369

**Comment by tusharnt** [comment]
@divyenpatel to update the documentation

**Comment by divyenpatel** [comment]
Updated `phase1/vsphere/README.md` : https://github.com/kubernetes/kubernetes-anywhere/pull/388

**Comment by divyenpatel** [comment]
Documentation updates Merged.
