### ISSUE TITLE
Scale test for PVC creation

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#127]
Create a high volume of PVC's with VSAN storage capabilities and check the amount of time taken for it.

I have a confluence page out for it - https://confluence.eng.vmware.com/display/CNAS/Scale+test+-+VSAN+policy+support+in+kubernetes

**Comment by BaluDontu** [comment]
References this issue - https://github.com/vmware/kubernetes/issues/122

**Comment by tusharnt** [comment]
This issue was tracking the task of creating the a scale test setup manually. This is already achieved.
