### ISSUE TITLE
support datastore cluster for vSphere Cloud Provider

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#129]
Add support for datastore cluster in vSphere Cloud Provider.
Ref PR: https://github.com/kubernetes/kubernetes/issues/44007

**Comment by divyenpatel** [comment]
PR: https://github.com/kubernetes/kubernetes/pull/44868

**Comment by BaluDontu** [comment]
Hey the documentation is missing in kubernetes#44868, can you please add it.

**Comment by divyenpatel** [comment]
Automated cherry pick PR: https://github.com/kubernetes/kubernetes/pull/45297

**Comment by divyenpatel** [comment]
Merged to release 1.6
