### ISSUE TITLE
Allow provisioning PVs without setting Units in the PVC spec 

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#130]
Ref PR: https://github.com/kubernetes/kubernetes/issues/43319

Customer reported - Unable to provision vSphere volume if PVC's requested size does not have unit.
The other provisioners allow a number only size for provisioning and assumes a default (usually gigs). This doesn't work in vsphere provisioned volumes.

if no unit is provided we will assume capacity requested is in the gigs and not in kb to avoid failing pv provisioning with fault - message = "The virtual disk size is too small."

**Comment by BaluDontu** [comment]
Currently, no Kubernetes volume plugin defaults the size of the disk to Gi. It is Bytes and is consistent across all volume plugins. 

Its upto the user specify the correct units for the disk size or other wise, we error out to the user. Also after @divyenpatel posted his PR to the community, the community doesn't want to default the size of disk specifically for one volume plugin which is us in this case. So this PR, is dropped altogether.

**Comment by divyenpatel** [comment]
summery from comments for better understanding. 

Unitless storage and memory requests always mean bytes.

non-zero requests less than 1GB result in a 1GB volume.
so in case of AWS and other provisioner, if user ask for 1,2, 100, 200... all provision a 1GB volume.

if case of vsphere, such smaller volume capacity results in to (vmodl.fault.InvalidArgument) - message = "The virtual disk size is too small."
