### ISSUE TITLE
Change way to fetch VM UUID from VM

### ISSUE THREAD

**Issue by abrarshivani** [vmware/kubernetes#132]
We fetch VM uuid using uuid reported at '/sys/devices/virtual/dmi/id/product_uuid'. This doesn't work with all the distros like Ubuntu 16.04 and Fedora. Hence, this need to be fix. One way to fix this using serial number ```/sys/class/dmi/id/product_serial``` and parsing it. 
Refer this: https://github.com/vmware/vic/blob/master/pkg/vsphere/guest/util_linux.go#L35

**Comment by divyenpatel** [comment]
PR: https://github.com/kubernetes/kubernetes/pull/45311

**Comment by divyenpatel** [comment]
PR merged and cherry picked to release 1.6
