### ISSUE TITLE
vSphere Cloud Provider Code Scrubbing Issues

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#134]
- [ ] vsphere.go → newVSphere()	
- [x] Check Null for working-dir
- [ ] Remove working Dir configuration all-together
- [ ] Test DataCenter name with Space.
- [ ] Check for non-empty values for all other configuration entries in vsphere.conf, including vCenter username and Password
- [ ] vCenter SDK Port -   need to check about "port is a deprecated field in vsphere.conf and will be removed in future release." . In the function newClient, we do not use port

- [ ] vsphere.go → getVMName()	
- [ ] Try out running kubelet on non-root user.
- [ ] VM UUID is retrieved from /sys/devices/virtual/dmi/id/product_uuid
- [ ] non-root user can not read this file.

- [ ] vsphere.go → checkIfDatastoreTypeIsVSAN()	
- We can use existing context, instead of creating new context every time.

- [ ] vsphere.go → AttachDisk()	
- vmDevices is getting overridden immediately.

- [ ] vsphere.go → getVirtualMachineDevices()
- Remove returning data center, as it is not appropriate in this function.

- [ ] vsphere.go→ list()	
- function does not seems to be used anywhere. Verify can we remove it?

- [ ] vsphere.go → ExternalID()
- this function seems deprecate. Needs to verified.

**Comment by divyenpatel** [comment]
PPT and Design Spec

https://confluence.eng.vmware.com/download/attachments/214946929/Design.xlsx?api=v2
https://confluence.eng.vmware.com/download/attachments/214946929/VSphereCPDesignRevised.pptx?api=v2

**Comment by casualjim** [comment]
These links are private on a public repo. They are so private that I can't see them in our own confluence. 
Can you put the files in a publicly accessible space?

**Comment by divyenpatel** [comment]
@casualjim  Here is the rough draft, we have created for our understanding. not a formal spec.

[Design.xlsx](https://github.com/vmware/kubernetes/files/1002667/Design.xlsx)
[VSphereCPDesignRevised.pptx](https://github.com/vmware/kubernetes/files/1002668/VSphereCPDesignRevised.pptx)

**Comment by divyenpatel** [comment]
Estimated Time for 1 Person Including Internal Review, Testing and Addressing Review Comments.

Connection Object - 2 Day
----------------------------

- [ ] Connect - 2 hours
- [ ] GetDatacenter() - 2 hours
- [ ] newClient() - 2 hours
- [ ] Generate PR - Address Review Comments - Revisit Code - 5 hours
- [ ] Testing against vCenter Server - 2 hours

VirtualMachine Object - 7 days
--------------------------------

- [ ] IsDiskAttached(datastore, diskPath string)  - 3 hours
- [ ] IsControllerAvailable(controllerType string) - 3 hours
- [ ] CreateAndAttachContoller(controllerType string) - 3 hours
- [ ] GetDeviceIDForDisk(diskPath) - 3 hours
- [ ] DeleteContoller(controllerType string) -3 hours
- [ ] FormatVirtualDiskUUID(diskUUID) - 3 hours
- [ ] GetVMProperty(property) - 2 hours						
- [ ] GetFolder(foldername) - 2 hours
- [ ]  getNextUnitNumber(devices object.VirtualDeviceList, c types.BaseVirtualController) - 2 hours
- [ ] GetSCSIControllersOfType(scsiType string) - 2 hours
- [ ]  GetSCSIControllers() []*types.VirtualController - 3 hours
- [ ] Generate PR - Address Review Comments - Revisit Code - 8 hours
- [ ] Testing against vCenter Server - 5 hours


Datastore Object - 4 days	
---------------------------

- [ ] Name() - 2 hours
- [ ] CreateDisk(context, path, vc.Datacenter(),  diskformat, capacity) - 5 hours
- [ ] CreateDirectory(dirpath) - 2 hours
- [ ] Generate PR - Address Review Comments - Revisit Code - 5 hours
- [ ] Testing against vCenter Server - 5 hours


Datacenter Object  - 4 days
-----------------------------

- [ ] GetVMByPath() - 2 hours
- [ ] GetVMByUUID(uuid) - 2 hours
- [ ] GetDatastore(ByName(datastorename)) - 2 hours
- [ ] GetDatastore(path) - 2 hours
- [ ] GetDatastoresFreeCapacity([] datastores) - 2 hours
- [ ] DatastoreByPath(volPath) - 2 hours
- [ ] Generate PR - Address Review Comments - Revisit Code - 5 hours
- [ ] Testing against vCenter Server - 5 hours


Package Utility - 3 days
-------------------------

- [ ] SearchProperty(object, moobject, fields….)  - 3 hours
- [ ] CreateDiskSpec() - 2 hours
- [ ] Generate PR - Address Review Comments - Revisit Code - 5 hours
- [ ] Testing against vCenter Server - 5 hours


vSphere Cloud Provider Utility - 3 days
----------------------------------------

- [ ] GetlocalIPs() - 2 hours
- [ ] IsIPProvidedByVMware(ip) - 2 hours
- [ ] GetVMUUIDfromFile() - 2 hours
- [ ] IsControllerSupported(controllerType) - 2 hours
- [ ] Generate PR - Address Review Comments - Revisit Code - 5 hours
- [ ] Testing against vCenter Server - 5 hours


Integration with Cloud Provider - 5 days
-----------------------------------------
e2e test updates and Validation - 5 days
-----------------------------------------

**Comment by divyenpatel** [comment]
- [ ] Revisit metric reporting code, and make it look clean. At present we are using named function, which does not look good to reviewer.
