### ISSUE TITLE
Change the Kubernetes-Anywhere Deployment Menu Options.

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#144]
@msterin suggested some changes for the deployment menu options for Kubernetes-Anywhere.

Current Menu is asking user to specify a cluster, host or a resource pool in which he wants to deploy Kubernetes Cluster. 

`Specify a valid Cluster, Host or Resource Pool in which to deploy Kubernetes VMs. (phase1.vSphere.resourcepool) [] (NEW)`

We have documented how the resource pool path looks like, but it is inconvenient to read up documentation, and build the path. We should change the Menu options to build up resource pool path for user. User just need to  enter the resource pool name.

Following is the change we want in the Menu options.

```
Deploy Kubernetes Cluster on 'host' or 'cluster' (phase1.vSphere.placement) [cluster] (NEW) cluster
    vspherecluster (phase1.vSphere.cluster) [] (NEW) cluster-vsan-1
Do you want to use resource pool created on host or cluster? [yes, no] (phase1.vSphere.useresourcepool) [no] (NEW) yes
    name of the resource pool [Provide Just a name] (phase1.vSphere.resourcepool) [] (NEW) dbResourcePool
```

Ideally we can ask user to fill up resource pool configuration, he wants to create, but currently terraform for vSphere does not support creating resource pool.
https://github.com/hashicorp/terraform/tree/master/builtin/providers/vsphere

Later when the support is available we can add Menu options to ask resource pool configurations and create the pool on the fly.

@BaluDontu @pdhamdhere @tusharnt

**Comment by msterin** [comment]
Thanks for writing it up. Are suggesting to fix host/cluster now , and add resource pool later , or so all later ?

**Comment by divyenpatel** [comment]
Fixing up, asking user to specify resourcepool name in which kubernetes cluster VMs should go in.
User can manually create the resource pool in the host or cluster, and provide just a name.

PR: https://github.com/kubernetes/kubernetes-anywhere/pull/391

Later we can add support in terraform to create resource pool. Since govmomi allows creating resource pool, we can add that support in terraform. Once we have terraform release with this support we can add menu options for user to specify resource pool configuration, and create it on the fly.
