### ISSUE TITLE
Implement vSphere cloud provider storage metrics

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#146]
Implement vSphere cloud provider storage metrics.

Ref: 

- https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cloudprovider-storage-metrics.md

**Comment by divyenpatel** [comment]
PR: https://github.com/kubernetes/kubernetes/pull/46462

**Comment by BaluDontu** [comment]
This PR is merged closing it.
