### ISSUE TITLE
Master node is removed before entering Ready state

### ISSUE THREAD

**Issue by yoshz** [vmware/kubernetes#165]
**Kubernetes version** (use `kubectl version`): 1.6.4

**Environment**:
- **Cloud provider or hardware configuration**: vSphere 6.5.0
- **OS**: CentOS 7.3
- **Kernel**: 3.10.0-514.21.1.el7.x86_64
- **Install tools**: Kubeadm and manual

**What happened**:
I bootstrapped a new cluster first by using kubeadm and later by manually deploying each step by hand. When controller-manager start the first time it removes the current node because it is not in Ready mode and the cloud provider says it does not exist, see line:
https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/node/nodecontroller.go#L683
After that it kubelet keeps on registering the node and controller-manager keeps on removing all pods (even itself) from the node.

**What you expected to happen**:
Controller-manager should startup and wait before the node is ready before checking the proud provider to remove it.
Also I would expect that the cloud provider should return that the node DOES exist and do nothing at all.

**How to reproduce it** (as minimally and precisely as possible):
Start controller-manager as manifest with the cloud provider enabled after you initially started kubelet and apicontroller (as manifest).

**Anything else we need to know**:
When I start controller-manager with cloud provider disabled initially and later on enable it, the problem does not exist.
Main problem seems to be that vSphere is saying that the node doesn't exist. Could this be a permission problem? I set the permissions described here: https://kubernetes.io/docs/getting-started-guides/vsphere/

**Comment by yoshz** [comment]
This also happens for each node I try to join:
```
W0615 10:54:40.127595       1 nodecontroller.go:947] Missing timestamp for Node of-dock-kn-005.funix.nl. Assuming now as a timestamp.
I0615 10:54:40.128640       1 event.go:217] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"of-dock-kn-005.funix.nl", UID:"054f902b-51b9-11e7-9b1f-005056a6facd", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RegisteredNode' Node of-dock-kn-005.funix.nl event: Registered Node of-dock-kn-005.funix.nl in NodeController
W0615 10:54:40.134234       1 vsphere.go:376] Creating new client session since the existing session is not valid or not authenticated
I0615 10:54:40.201594       1 event.go:217] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"of-dock-kn-005.funix.nl", UID:"054f902b-51b9-11e7-9b1f-005056a6facd", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'DeletingNode' Node of-dock-kn-005.funix.nl event: Deleting Node of-dock-kn-005.funix.nl because it's not present according to cloud provider
I0615 10:54:45.201840       1 event.go:217] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"of-dock-kn-005.funix.nl", UID:"054f902b-51b9-11e7-9b1f-005056a6facd", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'RemovingNode' Node of-dock-kn-005.funix.nl event: Removing Node of-dock-kn-005.funix.nl from NodeController
```

**Comment by divyenpatel** [comment]
@yoshz Can you share  `/etc/kubernetes/vsphere.conf `
Is your master node VM and other nodes present in the `working-dir` folder on VC?

One more thing, since you have configured this manually, can you enable UUID for a VM. You will need this later when you create a pod with volume.

`govc vm.change -e="disk.enableUUID=1" -vm=<VMNAME>`

**Comment by yoshz** [comment]
Not sure what you mean with working-dir (I am not a vSphere expert) but all files (vmdk, vms, vmsd) are stored in the same directory. We are using a NetApp storage and multiple ESX hosts.

I was able though to create a StorageClass and a PhysicalVolumeClaim which ended up in a PhysicalVolume later on when I enabled the cloud provider on the controller-manager when all nodes had state Ready. I saw the vmdk popup in vCenter on the configured datastore.

My vsphere configuration file is like this. Uuid is generated using the script I posted in this ticket: https://github.com/kubernetes/kubernetes/issues/44603#issuecomment-308353413

```
[Global]
    user = "*"
    password = "*"
    server = "10.40.6.19"
    port = "443"
    insecure-flag = "1"
    datacenter = "*"
    datastore = "vmdatastore2"
    vm-uuid = "42264EC1-EA31-57E1-2397-5148B588CC80"
[Disk]
    scsicontrollertype = pvscsi
```

**Comment by divyenpatel** [comment]
I assume your VMs are located in the root folder.

If VMs are located in the folder, as below, you have to specify  working-dir in vsphere.conf file.
`working-dir = "kubernetes"`

<img src='https://user-images.githubusercontent.com/22985595/27203304-13a5934e-51da-11e7-97de-c30b65e8cd45.jpg'/>

**Comment by divyenpatel** [comment]
Had a slack conversation with @yoshz, The working-dir setting has solved the problem.

But he can't mount a physical volume. The VMDK is created and attached to a VM, but when he start a pod with it, it ends up in these errors:

```
Jun 16 12:36:49 of-dock-kn-005 kubelet: Mounting command: mount
Jun 16 12:36:49 of-dock-kn-005 kubelet: Mounting arguments: /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[vmdatastore2] kubevols/kubernetes-dynamic-pvc-74624dc5-5290-11e7-b426-005056a67d72.vmdk /var/lib/kubelet/pods/747deb7c-5290-11e7-85df-005056a6dc2c/volumes/kubernetes.io~vsphere-volume/pvc-74624dc5-5290-11e7-b426-005056a67d72  [bind]
Jun 16 12:36:49 of-dock-kn-005 kubelet: Output: mount: special device /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[vmdatastore2] kubevols/kubernetes-dynamic-pvc-74624dc5-5290-11e7-b426-005056a67d72.vmdk does not exist
Jun 16 12:36:49 of-dock-kn-005 kubelet: E0616 12:36:49.122388   12570 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/vsphere-volume/747deb7c-5290-11e7-85df-005056a6dc2c-pvc-74624dc5-5290-11e7-b426-005056a67d72\" (\"747deb7c-5290-11e7-85df-005056a6dc2c\")" failed. No retries permitted until 2017-06-16 12:36:53.122355521 +0000 UTC (durationBeforeRetry 4s). Error: MountVolume.SetUp failed for volume "kubernetes.io/vsphere-volume/747deb7c-5290-11e7-85df-005056a6dc2c-pvc-74624dc5-5290-11e7-b426-005056a67d72" (spec.Name: "pvc-74624dc5-5290-11e7-b426-005056a67d72") pod "747deb7c-5290-11e7-85df-005056a6dc2c" (UID: "747deb7c-5290-11e7-85df-005056a6dc2c") with: mount failed: exit status 32
Jun 16 12:36:49 of-dock-kn-005 kubelet: Mounting command: mount
Jun 16 12:36:49 of-dock-kn-005 kubelet: Mounting arguments: /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[vmdatastore2] kubevols/kubernetes-dynamic-pvc-74624dc5-5290-11e7-b426-005056a67d72.vmdk /var/lib/kubelet/pods/747deb7c-5290-11e7-85df-005056a6dc2c/volumes/kubernetes.io~vsphere-volume/pvc-74624dc5-5290-11e7-b426-005056a67d72  [bind]
Jun 16 12:36:49 of-dock-kn-005 kubelet: Output: mount: special device /var/lib/kubelet/plugins/kubernetes.io/vsphere-volume/mounts/[vmdatastore2] kubevols/kubernetes-dynamic-pvc-74624dc5-5290-11e7-b426-005056a67d72.vmdk does not exist
Jun 16 12:36:49 of-dock-kn-005 kubelet: E0616 12:36:49.219710   12570 vsphere_volume_util.go:164] Cloud provider not initialized properly
```


I have suggested him to enable `disk.enableUUID` on all VMs. This should solve the problem.

`govc vm.change -e=“disk.enableUUID=1” -vm=<VMNAME>`

@yoshz, please close this issue, when you are able to mount the volume.

cc: @tusharnt @BaluDontu

**Comment by yoshz** [comment]
Enabling UUID solved the problem for mounting the disk. 
Well it all seems related to configuration problems from my side but for me it is not always clear what the problems is. Thanks for your help.

Can you tell me which vSphere permission you need for the vm.change command? The user I created for Kubernetes has not the right permissions to execute it.

**Comment by divyenpatel** [comment]
@yoshz if you **do not want to use administrator user** to enable UUID, please make sure, your user has following minimal privileges on the role to be able to set `disk.enableUUID=1` . Assign permission at VC level.

```
VirtualMachine.Config.AdvancedConfig
VirtualMachine.Config.Settings
```

```
$ govc role.ls change-uuid
System.Anonymous
System.Read
System.View
VirtualMachine.Config.AdvancedConfig
VirtualMachine.Config.Settings
```
