### ISSUE TITLE
Design spec - Multi VC and Multi Datacenter Support to vSphere Cloud Provider

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#173]
Add a Multi VC and Multi Datacenter Support to vSphere Cloud Provider

@BaluDontu @luomiao @rohitjogvmw @tusharnt

**Comment by tusharnt** [comment]
@rohitjogvmw Let's create an epic on our repo that describes detailed tasks for this feature.

**Comment by tusharnt** [comment]
Design is ready.
