### ISSUE TITLE
Simplify vSphere Cloud provider setup on existing kubernetes cluster

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#178]
Right now, in order to configure vSphere cloud provider on an existing kubernetes cluster set up, the following things need to be done:

- Enable UUID for VM
- Create a cloud config file for vSphere cloud provider
- Set the cloud provider via --cloud-provider=vsphere flag for each instance of kubelet, apiserver and controller manager
- Provide the cloud config file to each instance of kubelet, apiserver and controller manager via --cloud-config=<path to file> flag
- Restart the core kubernetes services

The idea to provide a script which will automate all the above steps instead of the user doing it manually.

@tusharnt @divyenpatel @rohitjogvmw @luomiao

**Comment by divyenpatel** [comment]
Kubernetes can be deployed many ways, Ansible, Kargo, Techtonic ...
So we can not have one generic script to configure vSphere cloud provider on all different platform.

To get started to help customer, we have following two approaches.

**Approach: 1**
For ansible coreos playbook - https://github.com/vmware/ansible-coreos-kubernetes-master/, 
YAML templates files are located on the deployment server- https://github.com/vmware/ansible-coreos-kubernetes-master/tree/master/templates 

- Create a go executable binary which takes VC username, password and Kubernetes Cluster working directory and default data store as an argument. Command will go through all VMs in the working directory, change VM configuration and sets disk.enableUUID to true.

- In the end, command will print vSphere.conf file, which needs to be placed in the Ansible CoreOS playbook configuration, to be pushed at specified location on master and other nodes.

- Once deployment is configured, yaml changes and vSphere.conf is pushed to master and nodes using ansible playbook.

Here we execute binary out side of cluster.

**Approach: 2**
In this Approach, we can extend the script and ask few more parameters.
Here we need to execute binary on the master node and other nodes.

After generating vsphere.conf file, script can add required parameters to the kube-controller-manager.json and kubelet.service file.

execute `systemctl daemon-reload`

and restart kubelet service and if node is the master node then restart controller manager container specified by `controller-container-id`

Script parameters looks like as below.
```
enable-vsphere-cloudprovider
	--enable-diskuuid
	--ismaster=true
	--vcusername='Administrator@vsphere.local'
	--vcpassword='Admin!23'
	--port='443'
	--manifests-kube-controller-manager='/etc/kubernetes/kube-controller-manager.json'
	--kubelet-service-config='/etc/systemd/system/kubelet.service'
	--controller-container-id='2d194319f200'
	--write-cloud-config=/etc/kubernetes/vsphere.conf
```

**Comment by divyenpatel** [comment]
The only issue, with approach 2 is how to restart kubelet service, if we plan to wrap this script in container image?

@luomiao @BaluDontu,  any sugeesion?
we can restart kubelet container, from docker container, but issue is we want to reload the config change we have made in /etc/systemd/system/kubelet.service

and for that, I need to execute `systemctl daemon-reload` on the host, which i think is not possible from the container.

**Comment by divyenpatel** [comment]
The issue mentioned above is resolved. we can reload and restart `kubelet.service` from within the container.

**Kubernets Master node  on Photon**

```
root@master [ ~ ]# uname -a
Linux master 4.4.8-esx #1-photon SMP Tue Jun 7 08:04:49 UTC 2016 x86_64 GNU/Linux
```



**Starting Fedora Container with mounting /run/system**
`root@master [ ~ ]# docker run -ti -v /run/systemd:/run/systemd fedora /bin/bash`

**Restarting container from within container**
```
[root@c685d65ec39b /]# systemctl restart kubelet.service
```

**Exited Container and checked status**
```
[root@c685d65ec39b /]# exit
exit
root@master [ ~ ]# docker ps | grep kubelet
1b15da9ad744        gcr.io/google-containers/hyperkube-amd64:v1.7.0-beta.2   "/hyperkube kubelet -"   8 seconds ago       Up 7 seconds                            reverent_franklin
root@master [ ~ ]#
```

We will see how we can achieve this with launching pod on each node.
@SandeepPissay

**Comment by divyenpatel** [comment]
Identified configurations steps for enabling vSphere cloud provider on clusters deployed using Kubeadm and Ansible playbook.

Comparisons/Differences is captured at https://confluence.eng.vmware.com/display/CNAS/Simplify+UX+for+configuration+of+vSphere+Cloud+Provider


Will explore Daemon Sets to create privileged pods on all nodes and master, to execute the script on all worker nodes and master node.

**Comment by BaluDontu** [comment]
@divyenpatel will create separate PR's for each of the tasks and will assign estimates for each of them.

**Comment by divyenpatel** [comment]
Created separate Issues for each of the tasks
https://github.com/vmware/kubernetes/issues/210 (Sprint Nemo) 
https://github.com/vmware/kubernetes/issues/211 (Sprint Nemo)
https://github.com/vmware/kubernetes/issues/212 (Sprint Dory)
https://github.com/vmware/kubernetes/issues/213 (Sprint Dory)
https://github.com/vmware/kubernetes/issues/214 (Sprint Dory)
https://github.com/vmware/kubernetes/issues/215 (Sprint Dory)

Closing this bug. We can track progress in above Issues.
