### ISSUE TITLE
Support VMs in multiple working directories in the same K8S cluster

### ISSUE THREAD

**Issue by luomiao** [vmware/kubernetes#187]
Currently we only allow VMs in the same working directory to join the same K8S cluster.
This is not a necessary limitation.
If the localInstanceID is set to Path+VMName at the very beginning, we should be able to support different workingDir VMs easily. Of course multiple functions need to be adjusted but this won't be a significant change.

**Comment by tusharnt** [comment]
It's still unclear what the priority of this issue is till we talk to the customer.

**Comment by SandeepPissay** [comment]
This will be address as part of supporting k8s spanning multiple VCs. I'm closing this issue. Feel free to reopen with valid reasons.
