### ISSUE TITLE
Cherry Pick PR to handles NPE when wrong UUID is specified in the vsphere.conf file

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#188]
We should cherry pick this PR - https://github.com/kubernetes/kubernetes/pull/44661 to release 1.5 and release 1.6 to handle NPE.

Recently a customer reported this issue, and we required to go through stack trace to root cause the problem.

with this PR, the correct error message is printed, instead of NPE stack trace.

cc: @tusharnt @BaluDontu @luomiao

**Comment by tusharnt** [comment]
Rohit will look into this with the highest priority.

**Comment by rohitjogvmw** [comment]
release-1.5: https://github.com/kubernetes/kubernetes/pull/49310
release-1.6: https://github.com/kubernetes/kubernetes/pull/49311

**Comment by divyenpatel** [comment]
Closing this issue. both PR are approved on kubernetes.
