### ISSUE TITLE
How to set disk.enableUUID=1 in VRA blueprint

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#189]
Customer uses VRA blueprint to provision Kubernetes node VMs and need information about how to set enableUUID property on the node VMs, automatically without touching vCenter.

@tusharnt @BaluDontu @luomiao

**Comment by BaluDontu** [comment]
In VRA, the template from which the kubernetes nodes are created can have the disk.enableUUID=1 . This way all the kubernetes nodes will have the disk UUID set by default.

**Comment by divyenpatel** [comment]
We will highlight this in pre-requisites sections, as most of the automation uses template VM to deploy kubernetes nodes. 

Will update this is in https://kubernetes.io/docs/getting-started-guides/vsphere/

**Comment by divyenpatel** [comment]
Updated Getting Started Guide and mentioned user can set `disk.enableUUID=1` on the template VM.
PR: https://github.com/kubernetes/kubernetes.github.io/pull/4418
