### ISSUE TITLE
VM name must match kubernetes resource name regex

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#200]
**Before enabling vSphere Cloud Provider**

```
-bash-4.1$ kubectl --context=nimbus get nodes
NAME                                      STATUS                     AGE
10.192.199.161                            Ready,SchedulingDisabled   5d
10.192.204.58                             Ready                      5d
10.192.221.63                             Ready                      5d
```

**After enabling vSphere Cloud Provider, node names changes to VM names**

```
$ kubectl --context=nimbus get nodes
NAME                                      STATUS                        AGE
divyenp-coreos112230-k8s145-111-ovfvm-1   Ready                         6m
divyenp-coreos112230-k8s145-111-ovfvm-2   Ready,SchedulingDisabled      15m
divyenp-coreos112230-k8s145-111-ovfvm-3   Ready                         2m
```

This mandates VM names must match to the `regex [a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)* `(e.g. 'example.com')  

**No upper case character is allowed in the node VM name**, else we can not enable vsphere cloud provider sucessfully.

We should document this in prerequisites if this is not going to be fixed soon.

cc: @BaluDontu @luomiao  @SandeepPissay @tusharnt

**Comment by casualjim** [comment]
the regex should be:
`^[a-zA-Z](([-0-9a-zA-Z]+)?[0-9a-zA-Z])?(\.[a-zA-Z](([-0-9a-zA-Z]+)?[0-9a-zA-Z])?)*$`

and it can't be shorter than 3 chars or longer than 63

it needs to be a valid dns segment

**Comment by divyenpatel** [comment]
We need to document this prerequisite. Customer ran into this issue when cluster is deployed on vsphere using kubespray - https://github.com/kubernetes/kubernetes/issues/48929

**Comment by divyenpatel** [comment]
Updated Getting Started Guide and added section for Node VM constraints
https://github.com/kubernetes/kubernetes.github.io/pull/4418
