### ISSUE TITLE
kubernetes documentation related issues

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#202]
Hi Girish, I have comments on k8s documentation that still needs to be addressed. I have reviewed first 2 sections. Below are still some of my open comments in these 2 sections.

- [x] The Edit me link doesn't work on any of the documentation pages.
- [ ] All the document names have no proper name instead have short forms. Using a better name would look good. 
- [x] The #vsphere-volume-pod.yaml in  http://vmware.github.io/docker-volume-vsphere/kubernetes/k8s-vols.html is not tab delimited at the start. Please remove it.
- [x] In Create Persistent Volume Claim section in http://vmware.github.io/docker-volume-vsphere/kubernetes/pv-pvc.html, the file is named wrong "vpshere-volume-pvc.yaml". Typo in vsphere word.
- [x] In http://vmware.github.io/docker-volume-vsphere/kubernetes/storageclass.html, the statement "vSAN storage capability parameters which you can specify explicitly. The newly created persistent volume will have these vSAN storage capabilities configured with it." should be a bullet point under parameters. Also the statement "There are additional parameters which are covered in Storage Policy Management section." should be added to the above statement not as a separate sentence. Overall it should look something like this
- [x] "vSAN storage capability parameters which you can specify explicitly. The newly created persistent volume will have these vSAN storage capabilities configured with it. vSAN storage capability parameters which are covered in Storage Policy Management section".
- [x] Make "Storage Policy Management section" a hyperlink to that section.
- [x] In http://vmware.github.io/docker-volume-vsphere/kubernetes/storageclass.html, Create Persistent Volume Claim Vsphere-volume-pvcsc.yaml got mixed up with the storage class describe. 
- [x] "kubectl describe pvc pvcsc001" section in page - http://vmware.github.io/docker-volume-vsphere/kubernetes/storageclass.html is not properly formatted. 
- [x] Seems like the entire page - http://vmware.github.io/docker-volume-vsphere/kubernetes/storageclass.html is not properly formatted.
- [x] In page - http://vmware.github.io/docker-volume-vsphere/kubernetes/spbm.html, "#sphere-volume-spbm-policy.yaml" file wrongly named.
- [x] In page - http://vmware.github.io/docker-volume-vsphere/kubernetes/spbm.html, Verify storage class is created got mixed up with Create Persistent Volume Claim.

@divyenpatel will review the remaining sections and provide his comments.
CC @tusharnt

**Comment by girishshilamkar** [comment]
I have fixed as per the comments. 
--
 "kubectl describe pvc pvcsc001" section in page - http://vmware.github.io/docker-volume-vsphere/kubernetes/storageclass.html is not properly formatted
--
Command outputs which are too long, will wrap around not sure how that can be formatted

I have raised a PR for it.
https://github.com/vmware/docker-volume-vsphere/pull/1596

**Comment by divyenpatel** [comment]
- [ ] Update http://vmware.github.io/docker-volume-vsphere/kubernetes/existing.html with 
[Enable vSphere Cloud Provider.pdf](https://github.com/vmware/kubernetes/files/1166989/Enable.vSphere.Cloud.Provider.pdf)

**Comment by divyenpatel** [comment]
All of the changes suggested above it taken care as part of following PRs

https://github.com/vmware/docker-volume-vsphere/pull/1755
https://github.com/vmware/docker-volume-vsphere/pull/1747
vmware/docker-volume-vsphere#1596

closing this issue.
