### ISSUE TITLE
Validate the VC restart scenario to check for node status inconsistencies

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#204]
Customer reported - When VC is powered off, Kubernetes v1.6.6. cluster remains stable.
Nodes remain active, Pods remain accessible.

But when VC is powered on back, after some time nodes started reporting disconnected / unavailable and back to available and ready state. Customer observed Pods were moving around from one node to another node.

We need to investigate this issue.

cc: @BaluDontu @tusharnt

**Comment by BaluDontu** [comment]
As part of first analysis, I have tried to reproduce the customer scenario by restarting the vpxd service and did the following steps:
- Deployed a kubernetes cluster on VC.
- Deploy multiple pods on the kubernetes cluster.
- Stop the vpxd services.
  -  Verified that the pods are still available and running.
- Restart the vpxd services.
  - Found the nodes are still in ready state and didn't observe any inconsistencies in node status.
  - Neither I observed the pods moving between the nodes as nodes are up and running.

Next steps:
 - I will now verify if I observe the same actions when VC is shutdown.

**Comment by BaluDontu** [comment]
I have verified to reproduce the customer scenario by shutting down the VC. I do not see any node consistencies (or) the pods moving between the nodes after a successful VC restart. 

Below steps are performed:
 - Create a 2 pod redis application with 1 volume attached to each pod.
 - Verified that I am able to access the frontend application.
 - Shut down the VC.
 - Verified that I am able to access the frontend application.
 - Restart the VC.
   - Verified that nodes are in Ready state only and pod also present in the same nodes as there were before shutting down the VC.
   - Also verified the logs to see any attach/detach operations on other nodes. I didn't find any of them.

Overall it seems to be working fine as expected. Will get back to the customer to verify if they can reproduce it on their environment and send the logs to the VMware team.

**Comment by BaluDontu** [comment]
Based on customer feedback, the customer is not able to reproduce the node inconsistencies in kubernetes release 1.6. Currently there are no other issues from the customer and they´re currently positive that the platform is stable for production workloads.
