### ISSUE TITLE
Heavy network traffic is observed in Kubernetes 1.5.x as compared to 1.6.x

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#205]
Customer observed that NetScaler has reported heavy network traffic in Kubernetes 1.5.x as compared to 1.6.x. Both setups have 1 volume attached to the node.

Customer has provided logs to analyze. We need to get back to the customer, as they are curious to know what has changed in a newer release.

cc: @BaluDontu @tusharnt

**Comment by BaluDontu** [comment]
The customer found with the kubernetes release 1.6 and above, he is not able to observe this issue at all. So, closing this issue as it doesn't any more analysis.
