### ISSUE TITLE
User guide for enabling vSphere Cloud Provider using Simplified UX - Daemonset approach

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#222]
Blog will explain how to begin with installation and configuration, which tasks are automated, where the source code is available and how community can help enhance this further.

This blog would be useful for Administrator or Developer who is getting started with Kubernetes vSphere Cloud provider and not using Kubernetes Anywhere for deployment.

@tusharnt

**Comment by divyenpatel** [comment]
Content is available at https://github.com/vmware/kubernetes/blob/enable-vcp-uxi/README.md

**Comment by divyenpatel** [comment]
Closing this Issue. Updated Guide as per @rohitjogvmw Review Comments.

**Comment by tusharnt** [comment]
1. Blog for UX improvements (which this issue is tracking) is not yet done.
2. The user guide is not linked in the customer facing documentation.
Hence reopening the issue.

**Comment by divyenpatel** [comment]
@tusharnt User guide for enabling VCP using automated scripts is linked on this page - https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html

2nd line

> All the steps mentioned below have been automated. For more details, please visit https://github.com/vmware/kubernetes/blob/enable-vcp-uxi/README.md. If pre-requisites are not applicable, then follow below steps manually.

**Comment by divyenpatel** [comment]
@rohitjogvmw has addressed this issue as part of https://github.com/vmware/vsphere-storage-for-kubernetes/pull/13/files#diff-e5ef072067c621514629e7382d090b04 

In the PR @rohitjogvmw has highlighted Automation as "Preferred method".

@tusharnt Is this sufficient?

**Comment by divyenpatel** [comment]
Addressed as part of https://github.com/vmware/vsphere-storage-for-kubernetes/pull/13
