### ISSUE TITLE
Populate VCP docs in "vsphere storage for kubernetes" repo

### ISSUE THREAD

**Issue by tusharnt** [vmware/kubernetes#226]
Populate VCP docs in "vsphere storage for kubernetes" repo - https://github.com/vmware/vsphere-storage-for-kubernetes

**Comment by divyenpatel** [comment]
Kubernetes documentation is pushed to the new repository on gh-pages branch.
https://github.com/vmware/vsphere-storage-for-kubernetes/tree/gh-pages
