### ISSUE TITLE
Octopus - Modify vsphere.conf file for specifying multiple virtual center details and create an in memory map

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#235]
Currently vSphere Cloud Provider (VCP) supports kubernetes cluster running on one Virtual Center (VC).
There are use cases where VCP needs to support kubernetes cluster spanning across multiple VCs.

First step needed is to change vSphere.conf file format which sould allow user to specify multiple virtual center details.
Reader code in VCP need to be modified accordingly

**Comment by SandeepPissay** [comment]
This issue is fixed & reviewed in PR - https://github.com/vmware/kubernetes/pull/308
