### ISSUE TITLE
Octopus - Discover kubernetes node in vSphere 

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#238]
Once vSphere Cloud Provider (VCP) running on master gets list of nodes, it need to Discover that node in vSphere. User can specify multiple Virtual Center details.  This can be a time consuming process.

For discovery, OS-UUID of the node should be used.

**Comment by abrarshivani** [comment]
Issue is resolved in PR: https://github.com/vmware/kubernetes/pull/320
