### ISSUE TITLE
Octopus - Modify CreateDisk API to make use of cached information (No SPBM support)

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#239]
During vSphere Cloud Provider (VCP) init vSphere.conf is read and kept in cache.
Use this cached information to identify default-datastore etc. parameters needed for the operation.

Note: This task is for just vanilla volume creation.
Volume creation with SPBM would be handled in separate task.

**Comment by rohitjogvmw** [comment]
This can not be completed in Sabastian sprint.
Moving out to Mcqueen sprint.

**Comment by SandeepPissay** [comment]
Fixed in PR - https://github.com/vmware/kubernetes/pull/358. Reviewed by @rohitjogvmw & @abrarshivani
