### ISSUE TITLE
Octopus - Modify Attach / Detach APIs to use cached information + Use SPBM Policy Name instead of policy ID.

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#241]
For Attach and Detach APIs nodename is passed as parameter,
Using cache, get the appropriate VM object and call operation on the VM object.

**Comment by rohitjogvmw** [comment]
Abrar will you be able to work on this?

**Comment by abrarshivani** [comment]
Will work on this

**Comment by abrarshivani** [comment]
PR merged: https://github.com/vmware/kubernetes/pull/335
