### ISSUE TITLE
Octopus - Rebuild / Rediscover node if VM object is not found on the vSphere

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#245]
If user moves kuernetes host VM from one datacenter to another then cached VM object will become stale and "ManagedObjectNotFOund" exception would be thrown from the virtual center.
Upon receiving ManagedObjectNotFound, try to rediscover the VM node in specified Virtual Center(s).

**Comment by rohitjogvmw** [comment]
This can not be completed in Sabastian sprint.
Moving out to Mcqueen sprint.

**Comment by abrarshivani** [comment]
PR Merged: https://github.com/vmware/kubernetes/pull/335
