### ISSUE TITLE
Photon Controller cloud provider: Using MAC address to figure out type of IP address

### ISSUE THREAD

**Issue by luomiao** [vmware/kubernetes#25]
NodeAddresses function should return the type of IP address along with IP addresses.
Currently force to return type of NodeInternalIP.
Should use MAC address to figure out the type.

**Comment by AlainRoy** [comment]
If you want to figure out if the MAC address is for an external NIC, you can look at the first three octets of the address. These are the OUI, which indicates the vendor that made the NIC. Private NICs have some OID (I forget what), while external NICs will have the VMware OUI. The two OUIs I've found are:

00:0c:29 (From ESX)
00:50:56 (From vCenter)

More details:
https://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.vsphere.networking.doc%2FGUID-DC7478FF-DC44-4625-9AD7-38208C56A552.html

http://pubs.vmware.com/vsphere-55/index.jsp?topic=%2Fcom.vmware.vsphere.networking.doc%2FGUID-1B6A280E-0C77-4775-8F84-4B3F40673178.html

**Comment by pdhamdhere** [comment]
CC/ @govint

**Comment by luomiao** [comment]
@AlainRoy 
Sorry to bring up this issue again since I am going to change this part of code.
So according to your comments, it looks like it's safe to set the IP address type to external if the MAC address prefix is "00:0c:29" or "00:50:56" for VMs started by photon controller rt?

**Comment by AlainRoy** [comment]
Yes, that's correct @luomiao.

**Comment by luomiao** [comment]
Done: https://github.com/kubernetes/kubernetes/pull/40843
