### ISSUE TITLE
Project Octopus - Multi VC and DC support for VCP

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#255]
Problem statement
--------------------

vSphere cloud provider in Kubernetes is designed to work only if all the nodes of the cluster are in one single datacenter folder. This is a hard restriction that makes the cluster not span across different folders/datacenter/VCs. You may want to span the cluster across datacenters/VCs for HA.

Current design
---------------

![multivcsupport-currentdesign2](https://user-images.githubusercontent.com/28635780/29899768-4d2de162-8da2-11e7-8110-b3478976a789.jpg)

**Current limitations**

Here's a list of limitations in the current VCP design:

1.  All nodes of the cluster must be under 1 VC datacenter folder  (implies under one datacenter and VC)
     VCP and vSphere.conf currently supports only 1 VC, 1 DC and 1 folder.

2.  VCP is not resilient to change of datacenter name, folder name, VM name.

3.  All nodes must specify vsphere.conf file. This file will need VC  credentials if VM name is not specified. If credentials or VM name changes, then things break. Fixing changes in credentials in all nodes is tedious. Similarly fixing VM names is manual and could be tedious. Note - worker nodes does not need the VC creds if VM name is specified. VCP in controller manager (master node) executes all the tasks like create/deleteDisk, attach/detachDisk, diskIs/Are/Present etc.  No use of vsphere.conf on worker nodes

4.  All nodes report their VM name as hostname. K8s expects hostname.
    UUID, IP Addresses and many more node specific details which is stored in etcd. Most of the VCP APIs are invoked by NodeName/VMName. This is how VCP in controller manager know the node name to attach/detach disk. Also there are some restrictions on the VM name (issue <https://github.com/vmware/kubernetes/issues/200>)

Proposed design change
--------------------------
**Design**

![multivcsupport-proposeddesign2](https://user-images.githubusercontent.com/28635780/29899748-2e68a2e4-8da2-11e7-9a65-1556067a867f.jpg)

- Every node will report it's hostname instead of VM name. Other properties like UUID, IP addresses etc are also reported.
- No need to have vsphere.conf in every node. Only master node will need it.

- VCP will get notified when nodes are added or removed via node controller in controller manager.
   Needs 2 additional methods in Instances interface (a change in cloud provider interface)
   The notification contains the node details reported in step (1).

- VCP in master discovers the nodes in the pool of VCs and maintains an in-memory cache.
   Master node will have all the VCs and VCP credentials in vsphere.conf
   In-memory cache entry will be invalidated if found invalid and refreshed with correct data dynamically.

**vsphere.conf**

VCP needs a pool of VCs specified in vsphere.conf. Create this file in master node only. This needs to be specified passed as cloud config to controller manager.

```
[Global]  # common property for all VCs
        user = "administrator@vsphere.local"
        password = "Admin!23"
        port = "443"
        insecure-flag = "1"
        datacenters = "vcqaDC"

[VirtualCenter "10.161.83.92"]  # 1st VC
      # Override username, password, port etc.  specific parameters if needed
      
[VirtualCenter "10.161.86.47"] # 2nd VC

[Workspace] # All the fileds are mandatory
        # For dummy VM (SPBM support) VCP needs one VC, datacenter in that VC, resource-pool needs to be specified.
        server = "10.161.83.92"
        datacenter = "vcqaDC"
        folder = "kubernetes"
        default-datastore = "sharedVmfs-2"
        resourcepool-path = "cls"

[Disk]
        scsicontrollertype = pvscsi

[Network]
        public-network = "VM Network"

```

**VCP user privileges**

The VCP roles and privileges are captured @ (https://github.com/divyenpatel/kubernetes.github.io/blob/2de598bf1fae224093425dccdc8bb0df0ee05774/docs/getting-started-guides/vsphere.md).
In addition/substitution we would need the following privileges:

1.  Read access on parent entities of the node VMs like folder, host, datacenter etc.
2.  VirtualMachine.Inventory.Create/Delete on the working directory. Used to create/delete dummy VMs.

**Building the cache in controller manager VCP**

During master node cloud-provider startup all nodes needs to be discovered and map needs to be created. Map will have nodeName to NodeInfo references.

The NodeInfo structure will contain:
- VC server
- VC username/pwd
- VirtualMachine identifier
- Datacenter identifier
- Default datastore etc

Apart from startup VCP needs to re-discover node(s) and update map in below cases:

- VCP will get node add/remove notifications from controller manager. The event contains the node details like hostname, UUID, IP address etc. VCP can discover the nodes in the pool of VCs using the UUID and IP address. Once discovered it will maintain a cache that can map hostname + UUID to NodeInfo

- Whenever node is moved from DC1 to another DC2 (when VCP gets ManagedObjectNotFound exception while executing VCP APIs against cache entries) 

- Whenever node is moved from VC1 to another VC2 (when VCP get ManagedObjectNotFound exception while executing VCP APIs against cache entries)

Above design will help VCP to support below

- Kubernetes clusters spanning across multiple datacenters and VCs. 

- vsphere.conf needed in only master node. Easy to deal with credential changes.

- The VMs could be created in any folder. Basically there is no working directory concept.
   For SPBM policy support user will still need to provide working-dir

- VMs could be vMotioned to any VC or datacenter as long as it is still part of the pool of VCs specified in vsphere.conf

- No restrictions on VM names

- Resilient to change in VM name, datacenter name and folder name.

Other considerations
----------------------

**SPBM policy name consistency**

If the user intends to use SPBM policy to create the volumes, the vSphere admin must make sure that the same SPBM policy exists in all VCs. This is a manual process since SPBM does not federate policies across VCs. If this is not the case then the AttachDisk will fail.

**Dummy VMs for SPBM policy support**

We create and cleanup dummy VMs as part of creating volumes. It will be easy to manage all this if we use the VC where the master node is running for this purpose. We can choose the DC where the master node is present. At first VCP can still consume working-dir on master node running VC to create SPBM policy dummy VM.

**Comment by prashima** [comment]
Closing this epic. Moved remaining issues to general pool.
