### ISSUE TITLE
Octopus - Update UX script to enable VCP for Multi-VC environments.

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#264]
Automate the testbed setup for Multi-VC.

Inorder to deploy a 4 node Kubernetes cluster, may be we can have a 3 VC setup with Master on 1 VC, 2 worker nodes on second VC and 2 other worker nodes on third VC.

**Comment by prashima** [comment]
Closing this issue. This will be taken care of by https://github.com/vmware/kubernetes/issues/408. The testbed described in issue description is not needed any more. #408 will provide configurable testbed deployment.
