### ISSUE TITLE
Octopus - Validate that volume creation does not happen on VSAN in Multi-VC scenario as VSAN is not common datastore

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#265]
The VSAN cluster is unique to a VC. We cannot have a shared VSAN cluster across multiple VC's. Hence we have to explicitly ensure that we cannot support Multi-VC feature is a VSAN datastore is provided by the user.

vSphere Cloud provider support on Multi-VC only works for NFS and VMFS datastores.

**Comment by SandeepPissay** [comment]
Closing this as this can be tested as part of create disk task
