### ISSUE TITLE
Octopus Integration testing - Develop new tests for Multi-VC

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#268]
Full round of Integration testing to test persistent volume support E2E.

To name a few, the tests would be
- Renaming datacenter, k8s node VM, cluster should not break k8s basic operations.
- Migrating k8s node VM from one datacenter to another should not break k8s basic operations.
- Migrating k8s node VM from one VC to another should not break k8s basic operations.

**Comment by tusharnt** [comment]
Let's use an epic for this.

**Comment by rohitjogvmw** [comment]
There are multiple tests needed for multi-vc.
It is tracked using below epic.
https://github.com/vmware/kubernetes/issues/378
