### ISSUE TITLE
E2E Test - Node power off test

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#272]
The following steps are required to perform this operation.

- Create a pod with a PVC.
- Power off the node where pod got provisioned.
- Verify the pod got provisioned on a different node with disks attached to it.
- Verify the disks are detached from powered off VM after 6 minutes.

**Comment by BaluDontu** [comment]
Unable to assign this issue to Abrar right now. Parking it in Tushar's plate now.

**Comment by shaominchen** [comment]
We need some new utility functions to support this test scenario: CreateDeployment, DeleteDeployment, GetPodForDeployment, etc. It takes some time to implement and test these functions. I'm filing a new issue for this dependency: #326

**Comment by shaominchen** [comment]
Updating the estimate as the node failover scenario is much more complicated than we expected.
