### ISSUE TITLE
Performance Tests

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#290]
Performance tests on vSphere Cloud Provider helps to verify the time it takes for volume lifecycle management against a benchmark. 

In this test we will verifying the time it takes to do each of the following operations and also the full time taken to compute all operations.
- Create volumes.
- Attach volumes to multiple pods on multiple nodes.
- Detach volumes on the nodes.
- Delete the volumes.

We will be performing the tests for dynamic volume provisioning with
- SPBM policy
- VSAN storage capabilities
- normal volume provisioning without any policy

**Comment by pshahzeb** [comment]
PR is out on Kubernetes https://github.com/kubernetes/kubernetes/pull/54092.
Closing this epic, will close the issue once PR is merged.
