### ISSUE TITLE
E2E Scale Tests - Create persistent volume at scale which is user configured

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#291]
Aim: Have a working test code which will create the volumes at scale and not determining the actual number of volumes that be created at scale.

The following actions will be performed as part of this test. 
- Create Storage class. We will create 4 storage classes.
  - SPBM policy
  - VSAN policy
  - Default datastore
  - User specified datastore
- Create Persistent volumes using storage class. The count of persistent volumes will be based on user configuration.
- Wait until all the persistent volumes are created.

**Comment by BaluDontu** [comment]
Internally reviewed and was approved by the team - https://github.com/vmware/kubernetes/pull/316
