### ISSUE TITLE
Octopus Integration testing - verify existing tests works for multiple VCs

### ISSUE THREAD

**Issue by SandeepPissay** [vmware/kubernetes#294]
Run the existing tests for multiple VCs and validate if they are working fine. Ideally they should just work fine.

**Comment by abrarshivani** [comment]
Verified existing e2e tests for multi-vc code. Jenkins log here: http://cna-storage-jenkins.eng.vmware.com:8080/job/k8s-release-multi-vc-validation/21/consoleText
