### ISSUE TITLE
Cherry-pick Bulk polling of volumes for vSphere implementation to 1.8 release

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#299]
Cherry-pick bulk polling of volumes for vSphere implementation - https://github.com/kubernetes/kubernetes/pull/41113 to 1.8 release.

**Comment by divyenpatel** [comment]
Cherry Pick PR: https://github.com/kubernetes/kubernetes/pull/54023

**Comment by divyenpatel** [comment]
kubernetes#54023 Merged.
