### ISSUE TITLE
Cherry-pick Bulk polling of volumes for vSphere implementation to 1.7 release

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#300]
Cherry-pick bulk polling of volumes for vSphere implementation https://github.com/kubernetes/kubernetes/pull/41113 to 1.7 release. Since 1.7 release branch doesn't have vsphere code refactoring changes, we have to implement this fix from scratch in 1.7 release.

**Comment by BaluDontu** [comment]
We need an approval from 1.7 branch manager before we can start working. It's because when we recently cherry-picked this request to 1.8 branch, there was a denial from the 1.8 branch manager as the code change is large. We have made a special request to 1.8 branch manager to approve it as it has an performance impact.

So before we go ahead with working on this fix, it is better we can get an approval from 1.7 branch manager.

**Comment by prashima** [comment]
cc @BaluDontu confirmed that branch manager for 1.7 denied request to add this big change as cherry pick.
