### ISSUE TITLE
kube-anywhere doesn't work with multiple resource pools

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#31]
I have a VC deployed with multiple clusters and hence multiple resource pools. I deployed the "KubernetesAnywhereTemplatePhotonOS" in one of the ESX boxes present in one of the clusters.

when I did make deploy, kube-anywhere fails to deploy and reports the following errors.

```
Error applying plan:

2 error(s) occurred:

* vsphere_virtual_machine.kubevm2: vm 'KubernetesAnywhereTemplatePhotonOS' not found
* vsphere_virtual_machine.kubevm1: vm 'KubernetesAnywhereTemplatePhotonOS' not found

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

Right now kube-anywhere doesn't take into consideration the resource pools as a config parameter that must provided to the user to be entered. This is in contrast with kube-up which needs a resource pool to be configured in order for kubernetes cluster to be created.

kube-anywhere right now works with single resource pool. 

@abrarshivani  @kerneltime @pdhamdhere

**Comment by BaluDontu** [comment]
Since there is no default resource pool in place, the user must provide in which resource pool to look for the template "KubernetesAnywhereTemplatePhotonOS" inorder to create the cluster.

**Comment by abrarshivani** [comment]
This error was due to ```KubernetesAnywhereTemplatePhotonOS``` not found since it was located in folder ```Discovered virtual machine``` and this was not mentioned in the config file. I moved template to root VM folder and then it was not able to resolve resource pool due to multiple instance of same. Hence, I got different error which is as follows,
```
Error applying plan:

2 error(s) occurred:

* vsphere_virtual_machine.kubevm2: default resource pool resolves to multiple instances, please specify
* vsphere_virtual_machine.kubevm1: default resource pool resolves to multiple instances, please specify

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

```

**Comment by BaluDontu** [comment]
While filling the config..
It asks for the - Template Name (phase1.vSphere.template) [KubernetesAnywhereTemplatePhotonOS]. This doesn't specify anything. Does the user have enough information that has be to path where the template is there on VC? 

Can you add more information to READ me for this.

**Comment by BaluDontu** [comment]
Fixed in https://github.com/kubernetes/kubernetes-anywhere/pull/293.
