### ISSUE TITLE
Encrypt vCenter server/port URL and vCenter username/password Credentials at Rest

### ISSUE THREAD

**Issue by ron1** [vmware/kubernetes#317]
/kind feature

**What happened**: The vCenter URL (server/port) and username/password are insecurely maintained in plain text in the vsphere.conf file.

**What you expected to happen**: The vCenter URL (server/port) and username/password are securely maintained in encrypted form to prevent these sensitive resources from being visible in plain text in a file on the file system.

**Environment**:
- Kubernetes version: 1.7
- Cloud provider or hardware configuration**: vSphere Cloud Provider

**Comment by dougm** [comment]
Opened an issue to consider alternatives, such as SAML token authentication: https://github.com/kubernetes/kubernetes/issues/63209

There are still details to be worked out, but support for token auth is near complete in govmomi.

**Comment by s0komma** [comment]
we would love to have this feature that way we can pass them in more secured fashion

**Comment by abrarshivani** [comment]
@s0komma This feature is added in PR: https://github.com/kubernetes/kubernetes/pull/63824. 
Closing this issue, since PR is merged.
