### ISSUE TITLE
Create E2E test branch for 1.8 release

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#331]
- Identify what tests can be executed on 1.8 branch.
- Make necessary test code changes to incorporate into e2e tests.
- Update existing Jenkins Build to use this new 1.8 branch

**Comment by BaluDontu** [comment]
Created a branch - E2ETests1.8branch for 1.8 release that has all E2E tests ported from master to this branch. Now E2ETests1.8branch has all the latest tests which can scheduled daily on a jenkins job. 

I have all the tests now running against the 1.8 branch and all the tests are passing.
