### ISSUE TITLE
vSphere Cloud Provider allows a persistent volume to be created on a non-shared datastore

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#339]
With the current implementation, vSphere cloud provider allows a persistent volume to be created on non-shared datastore which is accessible from master.

When a pod is provisioned using this persistent volume, it would provision a pod on a node which doesn't have access to this datastore. It that case, pod provisioning will fail as the volume is not accessible for attach.

So the solution would be to fail persistent volume creation when a user specifies a non-shared datastore or the default datastore is non-shared datastore.

**Comment by divyenpatel** [comment]
This restriction is already implemented. Closing this issue.

https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L1082

```

			// if the given datastore is a shared datastore across all node VMs.
			sharedDsList, err := getSharedDatastoresInK8SCluster(ctx, dc, vs.nodeManager)
			if err != nil {
				glog.Errorf("Failed to get shared datastore: %+v", err)
				return "", err
			}
			found := false
			for _, sharedDs := range sharedDsList {
				if datastore == sharedDs.Info.Name {
					found = true
					break
				}
			}
			if !found {
				msg := fmt.Sprintf("The specified datastore %s is not a shared datastore across node VMs", datastore)
				return "", errors.New(msg)
}
```
