### ISSUE TITLE
ubernetes attempts to unmount a wrong vSphere volume and stops making any progress after that #37022 kubernetes#37022

### ISSUE THREAD

**Issue by kerneltime** [vmware/kubernetes#34]
ubernetes attempts to unmount a wrong vSphere volume and stops making any progress after that #37022 kubernetes#37022

**Comment by pdhamdhere** [comment]
Fixed in master by #37413
Cherry-pick pending.

**Comment by BaluDontu** [comment]
#37867 - cherrypick PR.

**Comment by BaluDontu** [comment]
The cherry pick request #37867 is successfully merged. I think we can close this PR.
