### ISSUE TITLE
doc issue: 

### ISSUE THREAD

**Issue by guillierf** [vmware/kubernetes#346]
on this link:

https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/mongodb.html

YAML for storage class is incorrect:

kind: StorageClass
apiVersion: storage.k8s.io/v1beta1 
Metadata:
name: platinum
provisioner: Kubernetes.io/vsphere-volume
parameters:                 <========== MISSING
	diskformat: thin

**Comment by divyenpatel** [comment]
Thanks @guillierf We will fix documentation.

**Comment by pshahzeb** [comment]
Fixed through https://github.com/vmware/vsphere-storage-for-kubernetes/commit/663bd7945f1d1be67e453f199143bfbdaec6880e
