### ISSUE TITLE
Redirect VCP documentation on kubernetes.io to vsphere-storage-for-kubernetes repo

### ISSUE THREAD

**Issue by tusharnt** [vmware/kubernetes#362]
Currently we're duplicating the documentation for VCP in following git repos -
- https://kubernetes.io/docs/getting-started-guides/vsphere/
- https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/
Let's use vsphere-storage-for-kubernetes git repo as the central place to consolidate and maintain ALL VCP documentation.
This ensures our documentation efforts are not duplicated and customers always get access to the latest and accurate information.

**Comment by venilnoronha** [comment]
Fixed via kubernetes/website#7661.
