### ISSUE TITLE
Ability to specify different datastore directory in SC

### ISSUE THREAD

**Issue by souhradab** [vmware/kubernetes#364]
Currently vSphere Storage Provider creates all dynamic volumes in Datastore_Name/kubevols directory.  Requesting parameter in SC definition to specify a different volume for dynamic volumes.

#vsphere-volume-sc-example.yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: kubernetes.io/vsphere-volume
parameters:
    diskformat: zeroedthick
    **datastore: VSANDatastore** 

Need a parameter similar to: volumePath: "[datastore1] volumes/myDisk", such as when creating persistent volumes.

**Comment by rohitjogvmw** [comment]
Hi @souhradab,

This is by design.
vSphere Cloud Provider won't be providing a way to specify the location on Datastore.
There is no plan to support such such functionality.
