### ISSUE TITLE
Octopus Testing - Testing VCP supports master VM node migration to another VC

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#367]

**Comment by abrarshivani** [comment]
Manually tested: test executed successfully.
Test Done:
1. Migrated master VM to different VC.
2. Created PVC to provision volume dynamically.
3. Created pod using the volume.
4. Deleted pod.

Observation:
1. Pod was created successfully and volume was attached to it.
2. Pod was deleted and volume was detached successfully.

**Comment by shaominchen** [comment]
This will be covered by #365 and #366.
