### ISSUE TITLE
Octopus Testing -Testing VCP supports node VM migration to another VC

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#368]
Test steps:

1. Create storageclass and pvc to provision volume dynamically.
2. Migrated VM to different VC.
3. Created Pod with volume provisioned at step 1.
4. Executed command kubectl describe pod.

Expected result:
1. Volume got provisioned successfully.
2. Volume got attached successfully.

**Comment by abrarshivani** [comment]
Manually Tested this test. Got this issue https://github.com/vmware/kubernetes/issues/390 while testing.

**Comment by shaominchen** [comment]
This will be covered by #365 and #366.
