### ISSUE TITLE
Octopus Testing - Verify if VCP and K8S keeps running even if hostname and VM vsphere inventory name is different

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#370]

**Comment by abrarshivani** [comment]
Manually Tested: tested executed successfully

**Comment by shaominchen** [comment]
VM inventory name change will not trigger any real code workflow in VCP. So we will start with a testbed where the hostname and VM inventory name are different. Then all other test cases will verify this scenario implicitly.
