### ISSUE TITLE
Octopus testing - Verify VCP continues to run if VM vsphere inventory name is changed

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#375]

**Comment by abrarshivani** [comment]
Manually Verified test is successful.
Test Done:
1. Created K8s cluster configured with multi-vc.
2. Changed VM name in vSphere inventory.
3. Provisioned vSphere Volume and created pod using that volume.

Observations:
1. Verified that pod is scheduled on the node for which VM name was changed.
2. Pod was created successfully with volume attached.

**Comment by shaominchen** [comment]
VM inventory name change will not trigger any real code workflow in VCP. So we will start with a testbed where the hostname and VM inventory name are different. Then all other test cases will verify this scenario implicitly.
