### ISSUE TITLE
Octopus Testing - Verify VCP continues to run even if node vms (in different VCs) have same inventory name but different hostname 

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#376]

**Comment by abrarshivani** [comment]
Manually Verified test is successful.
Test Done:
1. Created K8s cluster with 2 nodes and 1 master configured with multi-vc.
2. Provisioned vSphere Volume. 
3. Migrated 1 node VM to different VC.
4. Changed VM name in vSphere inventory.
5. Created pod using that volume.

Observations:
1. Verified both nodes have different hostnames.
2. Pod was created successfully with volume attached.

**Comment by shaominchen** [comment]
VM inventory name change will not trigger any real code workflow in VCP. So we will start with a testbed where the hostname and VM inventory name are different. Then all other test cases will verify this scenario implicitly.

Also if later on anybody happen to introduce new changes that rely on VM inventory names, existing test cases should break and catch the regression.
