### ISSUE TITLE
Octopus Testing - Verify that VCP discovers newly added and removed k8s node

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#379]
Dividing this test into two sub tasks.   
- [ ] Node delete and add test
1.  Verify total Nodes present
2. Power off and delete node VM from vSphere inventory
3. Verify the given node above is removed
4. Add the node back to vSphere inventory and power it on

- [ ] Pod creation with dynamic provisioning after above test
1. Created pod with dynamically created vSphere volume
2. Deleted Pod

**Comment by abrarshivani** [comment]
Tested executed successfully.
Test Done:
1. Launched k8s cluster with multi-vc configuration.
2. Unregister node VM from vSphere inventory.
3. Restarted master by deleting etcd data.
4. Registered node VM back to vSphere inventory.
5. Created pod with dynamically created vSphere volume.
6. Deleted Pod.

Observed:
1. After registering node VM back found VM in nodes list.
2. Pod was successfully created with volume attached.
3. When pod was deleted volume got detached successfully.

**Comment by shaominchen** [comment]
Test Steps:
1. Run command kubectl get nodes to verify Node was present
2. Power off and delete node VM from vSphere inventory
3. Run command kubectl get nodes to verify Node was removed
4. Add the node back to vSphere inventory and power it on
5. Run command kubectl get nodes to verify Node was present
6. Created pod with dynamically created vSphere volume
7. Deleted Pod
