### ISSUE TITLE
Octopus Testing - Verify if VCP detects correctly if user deletes node vm from vsphere inventory without removing node from k8s cluster

### ISSUE THREAD

**Issue by rohitjogvmw** [vmware/kubernetes#380]

**Comment by abrarshivani** [comment]
Manually Verified test is successful.
Test Done:
1. Created K8s cluster configured with multi-vc.
2. Migrated node VM from one VC to another VC. (Rationale: To check if k8s sees this as node is deleted)
3. Deleted node VM from vSphere inventory. 

Observations:
1. After migration ran command ```kubectl get nodes```. Node was still present.
2. After node VM is removed, ran command ```kubectl get nodes```. Node was removed.

**Comment by shaominchen** [comment]
This has been merged with #379
