### ISSUE TITLE
Octopus Testing - Validate if Workspace parameters are honored

### ISSUE THREAD

**Issue by shaominchen** [vmware/kubernetes#382]
Master VM is running on VC-1 and Workspace specifies to use VC-2 for dummy creation 
Make sure that provisioning PV is happening using VC-2

**Comment by abrarshivani** [comment]
Manually tested this: https://github.com/vmware/kubernetes/issues/371 which also verifies this test.
Tested executed successfully

**Comment by shaominchen** [comment]
This is already covered by #371
