### ISSUE TITLE
Validate that VCP works with VVol datastores

### ISSUE THREAD

**Issue by tusharnt** [vmware/kubernetes#388]
As per @cormachogan, this is an important use case.
We need to document the results of our investigation.

**Comment by tusharnt** [comment]
@ashahi1 any update on this?

**Comment by divyenpatel** [comment]
Performed following to validate VVOL support for vSphere Cloud Provider.

- Deployed Kubernetes Cluster v1.8.4 on VVOL backed by iSCSi.
- Verified volume provisioning works well on VVOL backed by NFS.
- Created Statefulset with StorageClass and verified dynamic volume provisioning and volume attachment is successful.
- Executed vSphere Cloud Provider e2e test cases from E2ETests1.8branch branch. - https://github.com/vmware/kubernetes/tree/E2ETests1.8branch - All tests passed.

**Comment by tusharnt** [comment]
Doc updates - https://github.com/vmware/vsphere-storage-for-kubernetes/pull/10

**Comment by shay-berman** [comment]
Hello

Per this closed ticket I understand the PKS supports VVOL.  the PKS uses the "vSphere Cloud Provider" to provision storage inside PKS k8s cluster.

I have few questions about this verification and what does it mean for PKS support for VVOL:
1. Do we as storage vendor need to test VVOL with our backend storage together with vSphere Cloud Provider?  Of this ticket that verify it is enough? is there any specific certification storage vendor need to do here?
2. How the bind works? is it mount the vvol as filesystem on the specific worker node(or to all worker nodes at the same time?) and then k8s bind it to the POD\container? and when you stop the POD it unbind it and detach the VVOL?
3. When you create VVOL you should also mentioned VM name by the VVOL spec. So my question is what is the name given by using PKS? is it the VM name of the k8s worker node or is it the POD name?
4. The ticket mentioned iscsi and NAS. Did you also tested VVOL datastore on FC?

Thanks
