### ISSUE TITLE
Support large scale k8s clusters in VCP

### ISSUE THREAD

**Issue by tusharnt** [vmware/kubernetes#394]
As part of Project Octopus, VCP has been tested successfully with 12 node k8s clusters.
For customers looking to deploy large scale, production workloads, this scale needs to be much higher.

The aim of this issue as follows -

- [ ] Identify & document the maximum scale VCP can support today.

- [ ] Based on the customer input, identify the work items in VCP to support the requested maximum scale.

**Comment by tusharnt** [comment]
@rohitjogvmw found the following scale limits in [official k8s documentation](https://kubernetes.io/docs/admin/cluster-large/) -

- No more than 5000 nodes
- No more than 150000 total pods
- No more than 300000 total containers
- No more than 100 pods per node
 
For VCP, we will test with the above upper limits.

**Comment by divyenpatel** [comment]
Published configuration for 500 nodes scale testing at https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/largescaledeployment.html
