### ISSUE TITLE
doc issue

### ISSUE THREAD

**Issue by guillierf** [vmware/kubernetes#401]
in the  guestbook example
(https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/guestbook.html)

section "guestbook application with dynamic provisioning", the following command is missing:
$ kubectl create -f redis-master-pv.yaml create -f redis-slave-pv.yaml

(without this command, the REDIS-master and REDIS-slave POD cannot be created)

**Comment by divyenpatel** [comment]
@guillierf for dynamic provisioning we need to create stroage class and PV claim, PV will be created automatically.

so sequence should be

1. Create Storage Class
```
kubectl create -f redis-sc.yaml
```

2. Create PV claims
```
kubectl create -f redis-master-claim.yaml create -f redis-slave-claim.yaml
```

3. Create Pods with Claims
```
kubectl create -f guestbook-all-in-one.yaml 
```

For static Volume, we need to create PV manually using YAML files.

Steps mentioned at https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/guestbook.html looks good to me.

Let me know if you need any help.

cc: @tusharnt @BaluDontu 


Please Let me know if we can close this issue?

**Comment by guillierf** [comment]
@divyenpatel when I look at redis-master-pv.yaml file, it contains the volumepath where we can specify the datastore. 
How can the PVC figure our the volumepath if we don't create the PV before creating the PVC?

**Comment by divyenpatel** [comment]
@guillierf if you look at the yaml spec for the master and slave deployments, we use `persistentVolumeClaim` in the volume. Kubernetes can find PVs associated with PVC and finds `volumepath` from PV to attach with the node. 

https://github.com/vmware/kubernetes/blob/kube-examples/kube-examples/guestbook/guestbook-storageclass/guestbook-all-in-one.yaml#L62
https://github.com/vmware/kubernetes/blob/kube-examples/kube-examples/guestbook/guestbook-storageclass/guestbook-all-in-one.yaml#L132


You can read more about dynamic Provisioning and StorageClass API at https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/storageclass.html

**Comment by guillierf** [comment]
@divyenpatel I am still troubled because I am talking about the **vSphere datastore name**.
This one appears in the PV - but not in PVC nor in the master and slave deployments.

**Comment by guillierf** [comment]
@divyenpatel sorry got it. it's in the storage class.
