### ISSUE TITLE
vSphere CP Dynamic provisioning should not use white space

### ISSUE THREAD

**Issue by kerneltime** [vmware/kubernetes#41]
Related to https://github.com/vmware/kubernetes/issues/38
Till the bug is open we need to make sure dynamic provisioning works. Currently it introduces space between DS and Vol.

- [x] Create bug in k8s https://github.com/kubernetes/kubernetes/issues/38148

- [ ] Fix CP code

**Comment by BaluDontu** [comment]
white space is handled in the volumePath. This issue is fixed along with that issue. 

Fixed in #38
