### ISSUE TITLE
Kubernetes-anywhere doesn't launch cluster for 1.5.0 and master

### ISSUE THREAD

**Issue by abrarshivani** [vmware/kubernetes#42]
Hyperkube doesn't start kube-apiserver and kube-scheduler.

**Comment by abrarshivani** [comment]
I launched k8s-cluster with kubernetes master branch (commit d82e51edc5f02bff39661203c9b503d054c3493b) using kubernetes-anywhere.  I found that kubernetes api-server fails with an error 
``` 
E0111 03:00:53.829193   29597 status.go:62] apiserver received an error that is not an metav1.Status: rpc error: code = 13 desc = transport is closing
…
logging error output: "k8s\x00\n\f\n\x02v1\x12\x06Status\x12F\n\x04\n\x00\x12\x00\x12\aFailure\x1a0rpc error: code = 13 desc = transport is closing\"\x000\xf4\x03\x1a\x00\"\x00"
```
Currently, etcd3 is made as default storage backend for api-server and kubernetes-anywhere uses etcd2. Hence, this error occurs. This can be resolved by adding parameter ```storage-backend=etcd2``` to apiserver manifest. 

Referred this: https://github.com/kubernetes/kubernetes/issues/39710

I also found that sometimes kube-apiserver fails due to etcd starting after kube-apiserver starts. But, kube-apiserver is restarted, and it works second time.

**Comment by abrarshivani** [comment]
Also, we need to keep kubernetes (with master branch) re-testing using kubernetes-anywhere since some changes can make it fail.

**Comment by abrarshivani** [comment]
Created PR [here](https://github.com/kubernetes/kubernetes/issues/39710) which adds storage backend parameter.

**Comment by abrarshivani** [comment]
While launching kubernetes cluster with master branch using kubernetes-anywhere the script may not terminate. One reason for that could be that you may need updated version of kubectl in your kubernetes-anywhere container i.e one which you get after running ```make docker-dev```.

You can verify this by terminating the script and running following commands:
```
[container]:/opt/kubernetes-anywhere> export KUBECONFIG=phase1/vsphere/.tmp/kubeconfig.json
[container]:/opt/kubernetes-anywhere> kubectl get nodes
```
You would get error similar to the following,
```
error: group map[autoscaling:0xc8203d30a0 batch:0xc8203d3260 certificates.k8s.io:0xc8203d32d0 componentconfig:0xc8203d3340 extensions:0xc82022a070 federation:0xc8203d2930 authentication.k8s.io:0xc8203d2ee0 authorization.k8s.io:0xc8203d3030 policy:0xc82022a0e0 storage.k8s.io:0xc82022a1c0 :0xc8203d2e00 apps:0xc8203d2e70 rbac.authorization.k8s.io:0xc82022a150] is already registered
```

**Comment by pdhamdhere** [comment]
Fixed with https://github.com/kubernetes/kubernetes-anywhere/pull/326
