### ISSUE TITLE
Cherry picking PRs for 1.9.2

### ISSUE THREAD

**Issue by prashima** [vmware/kubernetes#420]
This issue is for tracking all the PRs that need to be cherry picked for 1.9.1.
@prashima to find out code freeze deadline for 1.9.1.
https://github.com/kubernetes/kubernetes/pull/57053

**Comment by shaominchen** [comment]
@prashima @abrarshivani @divyenpatel @BaluDontu @rohitjogvmw 
Can everybody share your PRs that need to be cherry picked for 1.9.1? It will save us a lot of time if we can do a bulk PR for all cherry picks.

My PR to be cherry picked: https://github.com/kubernetes/kubernetes/pull/56726

**Comment by abrarshivani** [comment]
My PR to be cherry-picked: https://github.com/kubernetes/kubernetes/pull/56648

**Comment by prashima** [comment]
In case it wasn't clear in my first comment on this issue...

My PR to be cherry-picked: kubernetes#57053 

Will add more, once I have a PR out.

**Comment by divyenpatel** [comment]
We need to cherry pick https://github.com/kubernetes/kubernetes/pull/57286 also to 1.9 once merged.

**Comment by shaominchen** [comment]
I have cherry picked all existing 3 PRs (#56648 from @abrarshivani,  #56726 from myself, #57053 from @prashima): https://github.com/kubernetes/kubernetes/pull/57482

I will share the cherrypick process (thanks @divyenpatel ) on our wiki so that somebody else can do the same for other pending PRs (once merged) following the same process.

**Comment by divyenpatel** [comment]
Cherry picked #57286 to 1.9: https://github.com/kubernetes/kubernetes/pull/57774

**Comment by shaominchen** [comment]
@divyenpatel Should we close this issue? Any remaining PRs to be crossported?

**Comment by divyenpatel** [comment]
Waiting for https://github.com/kubernetes/kubernetes/pull/57774 to be merged. then we can close this issue.

**Comment by divyenpatel** [comment]
https://github.com/kubernetes/kubernetes/pull/57774 is Merged on 1.9 branch. Closing this issue.
