### ISSUE TITLE
Explore upgrade to 1.9 multi-VC

### ISSUE THREAD

**Issue by prashima** [vmware/kubernetes#426]
Explore the behavior for upgrading a k8s cluster deployed on vSphere to 1.9.

Support matrix (Two dimensions of the problem)

- K8s version - 1.7 & 1.8
- K8s deployment mechanism - kube-anywhere, kubeadm

As part of addressing this issue assignee can:

- [x] First try upgrading manually and check the behavior during upgrade
- [x] Find out any extra steps required by user
- [x] Find out behavior for automated upgrade, if there is any story around it. Eg: check if kubeadm provides auto upgrade for k8s. If yes, how it works for upgrade to 1.9, for vSphere.

Post analysis, if needed, we should add another issue for automating test for upgrade.

**Comment by BaluDontu** [comment]
I am planning to do the following steps to explore the upgrading behaviour.

1. First try upgrading manually and check the behavior during upgrade
Part 1:
   - Deploy a multi-VC(M2N1) setup and use a single VC out of it for deploying a 1.8 kubernetes cluster. Verify basic VCP operations works.
   - Upgrade the kubernetes cluster to 1.9 kubernetes by updating the hyperkube image on Kubernetes core services (controller manager, kubelet etc.) on master and worker nodes. Here, no vsphere.conf file are performed. Verify basic VCP operations works.
   - Move some of the kubernetes nodes from VC1 to VC2. Use the 1.9 kubernetes cluster from step 2 and update vsphere.conf file on master node to use the latest vsphere.conf file format to specify the details of kubernetes nodes on both VC's. Verify basic VCP operations works.
 
    Part 2:
   - Deploy a multi-VC(M2N1) setup and use a single VC out of it for deploying a 1.8 kubernetes cluster. Verify basic VCP operations works.
   - Move some of the kubernetes nodes from VC1 to VC2. Upgrade the kubernetes cluster to 1.9 kubernetes by updating the hyperkube image on Kubernetes core services (controller manager, kubelet etc.) on master and worker nodes. Also update vsphere.conf file on master node to use the latest vsphere.conf file format to specify the details of kubernetes nodes on both VC's. Verify basic VCP operations works.

 2. Find out behavior for automated upgrade, if there is any story around it. Eg: check if kubeadm provides auto upgrade for k8s. If yes, how it works for upgrade to 1.9, for vSphere.
    - Verify kubeadm based approach of upgrading the kubernetes cluster from 1.8 to 1.9 and see if the basic VCP operations works. I need to figure this one out on how to do it.

CC @prashima

**Comment by prashima** [comment]
Few comments,

- In general, it would be beneficial to record steps, cluster state and spell out expectations for this whole exercise. Eg: 1.Part1 'Move some of the kubernetes nodes from VC1 to VC2' -> is kubelet stopped or running? What is the expected output here in terms of logs as well as actual cluster behavior? Similarly, for Part2, what is the expected behavior of cluster when nodes are moved to VC2, before performing the upgrade and making config file changes.

If we can generate a workflow from your exercise, then we will have a concrete thing to look at. If our customers comeback and say- "Upgrade is just not working!", we can ask them questions from these steps and check if they ended up with expected output/state or not (be is a faulty state).

- 1.Part1 > Here, no vsphere.conf file are performed.
Do you mean no vsphere.conf changes will be performed for this step?

**Comment by BaluDontu** [comment]
>>>1.Part1 > Here, no vsphere.conf file are performed.
Do you mean no vsphere.conf changes will be performed for this step?
Yes.
Few comments,

>>>In general, it would be beneficial to record steps, cluster state and spell out expectations for this whole exercise. Eg: 1.Part1 'Move some of the kubernetes nodes from VC1 to VC2' -> is kubelet stopped or running? What is the expected output here in terms of logs as well as actual cluster behavior? Similarly, for Part2, what is the expected behavior of cluster when nodes are moved to VC2, before performing the upgrade and making config file changes.
We don't need to stop the kubelet for moving the nodes. We can prepare the node for maintenance, marking it unschedulable and evicting the workload using "kubectl drain $NODE" and later after successful migration to target VC, we can uncordon the node using "kubectl uncordon $NODE". I will add the steps in detail.

Overall, does Part1 and Part2 steps sounds good?

**Comment by prashima** [comment]
Yes, they look fine to me. 

Want to add one more point- please make sure that we check logs for any errors for both master and workers.

**Comment by BaluDontu** [comment]
First try upgrading manually and check the behavior during upgrade

Part 1:
- Deploy a multi-VC(M2N1) setup and use a single VC out of it for deploying a 1.8.6 kubernetes cluster. Verify basic VCP operations works.
   - Deployed a basic guestbook (redis) application with frontend and backend where volume is backed by vsphere volume. All the create, attach, detach and delete operations works perfectly fine.
   - Accessed the frontend application to add some messages into the guestbook. All the messaged are saved on multiple redeployments.
-  Upgrade the kubernetes cluster to 1.9.1 kubernetes by updating the hyperkube image on Kubernetes core services (controller manager, kubelet etc.) on master and worker nodes. Here, no vsphere.conf file are performed. Verify basic VCP operations works.
   - The following steps are performed on master.
      - Update the hyperkube image on controller-manager, api-server and scheduler manifest files.
        - `$ sed -i "s~gcr.io/google-containers/hyperkube-amd64:v1.8.6~docker.io/hyperkube-amd64:v1.9.1~g" kube-apiserver.json`
        - `$ sed -i "s~gcr.io/google-containers/hyperkube-amd64:v1.8.6~docker.io/hyperkube-amd64:v1.9.1~g" kube-controller-manager.json`
        - `$ sed -i "s~gcr.io/google-containers/hyperkube-amd64:v1.8.6~docker.io/hyperkube-amd64:v1.9.1~g" kube-scheduler.json`
      - Update the hyperkube image on kubelet service.
         -  `$ sed -i "s~gcr.io/google-containers/hyperkube-amd64:v1.8.6~docker.io/hyperkube-amd64:v1.9.1~g" /etc/systemd/system/kubelet.service`
    - The following steps are performed on all worker nodes.
       - Update the hyperkube image on kubelet service.
         -  `$ sed -i "s~gcr.io/google-containers/hyperkube-amd64:v1.8.6~docker.io/hyperkube-amd64:v1.9.1~g" /etc/systemd/system/kubelet.service`
    - Reload the kubelet service to pick up the latest changes and restart the kubelet service on all the nodes including master.
       - `$ systemctl daemon-reload`
       - `$ systemctl restart kubelet`
    - In this case, no vsphere.conf is updated.
    - Verified the kubectl get nodes shows the latest kubernetes version deployed.
       - `$ kubectl get nodes`. Verify the VERSION is 1.9.1
    - All the create, attach, detach and delete operations works perfectly fine as expected.
    - Also verified the messages added in guestbook before upgrade were available after the upgrade.    
- Move some of the kubernetes nodes from VC1 to VC2. Use the 1.9 kubernetes cluster from step 2 and update vsphere.conf file on master node to use the latest vsphere.conf file format to specify the details of kubernetes nodes on both VC's. Verify basic VCP operations works.
  - Prepare the host for maintenance, marking it unschedulable and evicting the workload
    - `$ kubectl drain $NODE --ignore-daemonsets`
    -  When running this command against the master host, this error is expected and can be safely ignored (since there are static pods running on the master):
  - Migrate the node(s) from VC1(current) to VC2(new). Both these VC's share same datastores.
  - After successful migration, check the status of the kubelet.
     - `$ systemctl status kubelet`
  - Bring the node back online by marking it schedulable
     - `$ kubectl uncordon $HOST `
  - Update the vsphere.conf on master node at location /etc/kubernetes/vsphere.conf. Make sure you use the new vsphere.conf format that let's the VCP know about the nodes that are deployed in multiple VC's.
  - Restart the kubelet on master.
     - `$ systemctl restart kubelet`
  - Verified the messages added in guestbook before upgrade were available after the upgrade.
  - Added some additional messages in the guestbook app to see if the messages are being persisted.
  - All the create, attach, detach and delete operations works perfectly fine as expected.

Part 2:

- Deploy a multi-VC(M2N1) setup and use a single VC out of it for deploying a 1.8 kubernetes cluster. Verify basic VCP operations works.
   - Deployed a basic guestbook (redis) application with frontend and backend where volume is backed by vsphere volume. All the create, attach, detach and delete operations works perfectly fine.
   - Accessed the frontend application to add some messages into the guestbook. All the messaged are saved on multiple redeployments.
- Move some of the kubernetes nodes from VC1 to VC2. Upgrade the kubernetes cluster to 1.9 kubernetes by updating the hyperkube image on Kubernetes core services (controller manager, kubelet etc.) on master and worker nodes. Also update vsphere.conf file on master node to use the latest vsphere.conf file format to specify the details of kubernetes nodes on both VC's. Verify basic VCP operations works.
  - Prepare the host for maintenance, marking it unschedulable and evicting the workload
    - `$ kubectl drain $NODE --ignore-daemonsets`
    -  When running this command against the master host, this error is expected and can be safely ignored (since there are static pods running on the master):
  - Migrate the node(s) from VC1(current) to VC2(new). Both these VC's share same datastores.
  - After successful migration, check the status of the kubelet.
     - `$ systemctl status kubelet`
  - Bring the node back online by marking it schedulable
     - `$ kubectl uncordon $HOST `
   - The following steps are performed on master.
      - Update the hyperkube image on controller-manager, api-server and scheduler manifest files.
        - `$ sed -i "s~gcr.io/google-containers/hyperkube-amd64:v1.8.6~docker.io/hyperkube-amd64:v1.9.1~g" kube-apiserver.json`
        - `$ sed -i "s~gcr.io/google-containers/hyperkube-amd64:v1.8.6~docker.io/hyperkube-amd64:v1.9.1~g" kube-controller-manager.json`
        - `$ sed -i "s~gcr.io/google-containers/hyperkube-amd64:v1.8.6~docker.io/hyperkube-amd64:v1.9.1~g" kube-scheduler.json`
      - Update the hyperkube image on kubelet service.
         -  `$ sed -i "s~gcr.io/google-containers/hyperkube-amd64:v1.8.6~docker.io/hyperkube-amd64:v1.9.1~g" /etc/systemd/system/kubelet.service`
    - The following steps are performed on all worker nodes.
       - Update the hyperkube image on kubelet service.
         -  `$ sed -i "s~gcr.io/google-containers/hyperkube-amd64:v1.8.6~docker.io/hyperkube-amd64:v1.9.1~g" /etc/systemd/system/kubelet.service`
    - Reload the kubelet service to pick up the latest changes and restart the kubelet service on all the nodes including master.
       - `$ systemctl daemon-reload`
       - `$ systemctl restart kubelet`
    - Verified the kubectl get nodes shows the latest kubernetes version deployed.
       - `$ kubectl get nodes`. Verify the VERSION is 1.9.1
  - Update the vsphere.conf on master node at location /etc/kubernetes/vsphere.conf. Make sure you use the new vsphere.conf format that let's the VCP know about the nodes that are deployed in multiple VC's.
  - Restart the kubelet on master.
     - `systemctl restart kubelet`
  - Verified the messages added in guestbook before upgrade were available after the upgrade.
  - Added some additional messages in the guestbook app to see if the messages are being persisted.
  - All the create, attach, detach and delete operations works perfectly fine as expected.

**Comment by prashima** [comment]
Comments for part 1: 
- Looks like the error you wanted to post is missing here-

> When running this command against the master host, this error is expected and can be safely ignored (since there are static pods running on the master):

- It's not clear if you tried scheduling the pod on the migrated node or not. Can you please clarify? Scheduling should be tried on the migrated node so that we know that new VC is getting connected to and cached.

**Comment by BaluDontu** [comment]
Kubeadm testing is successfully completed and all the instructions has been updated in our documentation site - https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/kubernetes-upgrade.html

PR to update the documentation to include upgrade instructions - https://github.com/vmware/vsphere-storage-for-kubernetes/pull/24

PR to generate the HTML for kubernetes upgrade instructions - https://github.com/vmware/vsphere-storage-for-kubernetes/pull/25
