### ISSUE TITLE
E2E tests to not use production code for volume operations

### ISSUE THREAD

**Issue by BaluDontu** [vmware/kubernetes#434]
Currently vSphere E2E test cases uses VCP production code for bootstrap logic, example is to get an instance of vSphere struct. Once it gets an instance vSphere struct, it will use this object to call into methods in VCP code like - DiskIsAttached(), DisksAreAttached() etc.

This direct dependency on the VCP production should be removed as any changes to the production code would create a problem in E2E test cases as well.

**Comment by pshahzeb** [comment]
Production code packages imported are vclib and vsphere: Following  functions are directly used
```
1. vsphere.GetgovmomiClient
2. vsphere.GetVSphere()
```
Struct used directly
`1. vclib.VolumeOptions `


Once vsp object us created using vsphere.GetVSphere() function. Following are the production code functions used directly:
```
vsp.DisksAreAttached()
vsp.CreateVolume()
vsp.NodeAdded()
vsp.DiskIsAttached()
vsp.DeleteVolume()
```

**Comment by divyenpatel** [comment]
Internal PR out for review: https://github.com/vmware/kubernetes/pull/456

**Comment by divyenpatel** [comment]
PR Merged: https://github.com/kubernetes/kubernetes/pull/59761
