### ISSUE TITLE
Implementation of NodeVM-VC map and use it in new/existing tests

### ISSUE THREAD

**Issue by pshahzeb** [vmware/kubernetes#437]
This issue tracks the need of node discovery to populate map of K8s node VMs to the VC in which they reside. After multi-VC feature, we need this and can't rely on the fact that all VMs reside on a given VC.

This discovery needs to be done once before launching the entire vsphere test suite.
This issue also tracks using this discoverymap in existing test files and modify them to make sure nothing breaks.

- [x] Implement bootstrapping logic for vsphere tests. Should be called by all the tests but executed only once for whole suite (2) - internal review done
- [x] Implement configuration reading and node discovery logic. (2)

**Comment by divyenpatel** [comment]
> This discovery needs to be done once before launching the entire vsphere test suite.

We can add common provider specific initialization which needs to be invoked only once for all tests here - https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L53  

This is being called from - `ginkgo.SynchronizedBeforeSuite` at https://github.com/kubernetes/kubernetes/blob/master/test/e2e/e2e.go#L138

**Comment by divyenpatel** [comment]
2nd of part of the tasks listed in the issue description is pending. @prashima is working on this.
