### ISSUE TITLE
Typo in VCP

### ISSUE THREAD

**Issue by embano1** [vmware/kubernetes#446]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Typo in VCP. `s/Google/VMware`

```
// Zones returns an implementation of Zones for Google vSphere.
func (vs *VSphere) Zones() (cloudprovider.Zones, bool) {
	glog.V(1).Info("The vSphere cloud provider does not support zones")
	return nil, false
}
```
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vsphere.go#L674

**What you expected to happen**:
Correct description.

**How to reproduce it (as minimally and precisely as possible)**:
n/a

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by divyenpatel** [comment]
Pull Request : https://github.com/kubernetes/kubernetes/pull/65508
