### ISSUE TITLE
Validate all container host OSes against Virtual hardware version 13

### ISSUE THREAD

**Issue by tusharnt** [vmware/kubernetes#450]
Validate all container host OSes against Virtual Hardware version 13 and update customer facing documentation.
Fix VCP issues uncovered if any.

**Comment by divyenpatel** [comment]
Here is my observations.

**VM version 13**
- New VM  created from ISO - `product_serial` and `product_uuid` **does not match.**
- New VM created from OVA -  `product_serial` and `product_uuid` **does match**.

**VM version 11**
- New VM created from ISO -`product_serial` and `product_uuid` **does match.**
- New VM created from OVA - `product_serial` and `product_uuid` **does match**.


CC: @SandeepPissay

**Comment by SandeepPissay** [comment]
As we discussed, let us use product_serial in the OS and use that for discovering the node. Since this always matches the VM's uuid in VC inventory, the discovery will be successful.

**Comment by prashima** [comment]
This needs to be cherry-picked to 1.9.

**Comment by abrarshivani** [comment]
Cherrypicked to 1.9 [here](https://github.com/kubernetes/kubernetes/pull/59602)

**Comment by abrarshivani** [comment]
Documentation PR and Cherrypick PR is merged. The fix is available in k8s v1.9.4
