### ISSUE TITLE
Missing documentation about if vCenter is a prerequisite to use the cloud provider?

### ISSUE THREAD

**Issue by dniel** [vmware/kubernetes#465]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
Tried to follow the example code to create persistent storage using the the vSphere Cloud Provider on a standalone ESXi host but failed to get it working, then I tried to read the documentation about vSphere Cloud Provider to find out if vCenter is required, but cant find any information in the documentation if it is possible to run the provider without vCenter installed.

**What you expected to happen**:
Find some clear guidelines in the documentation about if vCenter is required to run vSphere Cloud Provider.

**How to reproduce it (as minimally and precisely as possible)**:
Open the documenation and go to the page where it is documented if vCenter is required.

**Anything else we need to know?**:
Please add a point to the documentation to make it clear if it is required to install vCenter to get this working, or if it is possible to run it on a standalone ESXi host.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration: ESXI 6.5 standalone host without vCenter.
- OS (e.g. from /etc/os-release): Coreos.
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by abrarshivani** [comment]
@dniel Thanks for trying out vSphere Cloud Provider. We need vCenter for using vSphere Cloud Provider. Just wondering which documentation you looked at?
We have that documented here: https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/prerequisites.html

**Comment by dniel** [comment]
@abrarshivani yes, the link you provided is the page I read. When reading the documentation, the code and configuration there are alot of references to vsphere and vcenter but could not find any clear advice that is wont work on a standalone esxi host. 

When re-reading the prerequisite page, I now see the bullet point "vCenter user with required set of privileges." which could be interpreted to mean that a standalone ESXi host would not work. To make this more clear I would propose to add a point to that list "ESXi host managed by vCenter"

**Comment by abrarshivani** [comment]
@dniel Thank you for the feedback. This is been fixed here https://github.com/vmware/vsphere-storage-for-kubernetes/pull/28
