### ISSUE TITLE
Improve VCP Documentation for different Kubernetes versions

### ISSUE THREAD

**Issue by embano1** [vmware/kubernetes#479]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**:
Improve VCP documentation (https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/index.html).

**What you expected to happen**:
As discussed with @divyenpatel 

- Separate tables/pages for Kubernetes version (clarity)
- Document how VCP needs to be configured in Kubernetes v1.9
  - Only master(s) need(s) vsphere.conf with credentials
  - Worker just need `--cloud-provider=vsphere` flag (no credentials, reducing attack surface on credentials)
  - Make it clear that masters do not have to run `kubelet` for VCP to work
- Document behavior and necessity of certain parameters in vsphere.conf depending on Kubernetes version
  - vm-name
  - UUID
  - which parameters have to be set on master/worker
  - which parameters need credentials on worker (e.g. running Kubernetes <1.9)
- Document upcoming changes/improvements around secret handling (avoid plaintext credentials)
- Avoid exposing credentials `secret` to DaemonSet running on workers when using VCP UX deployment script/mechanism
- Make it clear that for different PV features, different restricted roles and permissions can be applied. Currently most people oversee the advanced permissions table and rely on the table provided [here](https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html), which has the most permissions required to run dynamic PVs with SPB volume placement. Move [examples](https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html) to main page.
 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alesz** [comment]
Followed improved documentation for deployment of k8s 1.9, having trouble understanding datacenters variable in case of whitespace in the name. Example expected vsphere.conf:
```
[Global]
user = "k8s_service"        
password = "xxxx"        
port = "443"        
insecure-flag = "1"        
datacenters = "First DataCenter, Second DataCenter"
# or
# datacenters = { "First DataCenter", Second DataCenter" }
# or
# datacenters = "First DataCenter" "Second DataCenter"


[VirtualCenter "first.dc.example.com"]
[VirtualCenter "second.dc.example.com"]

[Disk]
scsicontrollertype = pvscsi
```

**Comment by embano1** [comment]
@alesz whitespaces should be handled correctly, e.g. here's the code for v1.9 VCP:

```go
datacenters := strings.Split(vsi.cfg.Datacenters, ",")
				for _, dc := range datacenters {
					dc = strings.TrimSpace(dc)
					if dc == "" {
						continue
					}
```
https://github.com/kubernetes/kubernetes/blob/release-1.9/pkg/cloudprovider/providers/vsphere/nodemanager.go#L135

**Comment by MQasimSarfraz** [comment]
:+1: 

Also do we need `vsphere.conf` on worker nodes for > 1.9 ?

**Comment by embano1** [comment]
@MQasimSarfraz just the `--cloud-provider` flag for kubelet.

**Comment by MQasimSarfraz** [comment]
Thanks @embano1. Some installers e.g kubespray are still putting them on worker nodes. So needs to be updated.

**Comment by divyenpatel** [comment]
Addressed Requested Changes with this PR - https://github.com/vmware/vsphere-storage-for-kubernetes/pull/39
