### ISSUE TITLE
setup of vsphere-storage-for-kubernetes fails with controller-manager crashing 

### ISSUE THREAD

**Issue by s0komma** [vmware/kubernetes#480]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind feature

**What happened**:
Trying to use vsphere datastore for k8s persistent storage, i have followed every thing listed in https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html, steps listed under manual steps.  But after doing all the steps, the controller-manager keeps crashing with below error 
`Apr 26 22:07:09 XXXXX  kube-system_kube-controller-manager-XXXXX[14960]: F0426 22:07:09.747554       1 plugins.go:114] Couldn't open cloud provider configuration /etc/kubernetes/cloud-config/vsphere.conf: &os.PathError{Op:"open", Path:"/etc/kubernetes/cloud-config/vsphere.conf", Err:0x2}`
we have tried placing the file under `/etc/kubernetes/` `/etc/kubernetes/pki` & `/etc/kubernetes/cloud-config/` and still ends up with same issue. 
**What you expected to happen**:
controller-manager pod to be up and running 
**How to reproduce it (as minimally and precisely as possible)**:
place the config file under controller-manager manifest 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.7
- Cloud provider or hardware configuration: Vmware
- OS (e.g. from /etc/os-release):NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`): Linux us06000c3-datanode-001 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by divyenpatel** [comment]
@s0komma 
From the message, looks like kube-controller-manager pod can not open `/etc/kubernetes/cloud-config/vsphere.conf` file. 

Can you mount `/etc/kubernetes/cloud-config` on the controller-manager pod?

**Comment by s0komma** [comment]
Thank you @divyenpatel for pointing in right direction.. its working now.. Thank you ..
