### ISSUE TITLE
unable to create dynamic pvc using storage class  

### ISSUE THREAD

**Issue by s0komma** [vmware/kubernetes#481]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind feature

**What happened**: After following all the manual steps listed in document, while trying to create volume using storage class getting below error in controller-manage. tried updating the vsphere.conf file to use IP and hostname, but had same result  
`Apr 30 21:00:56 XXXXX-master-k8-01 kube-system_kube-controller-manager-xxxxx-master-k8-01[14960]: I0430 21:00:56.580616       1 vsphere.go:1032] Starting to create a vSphere volume with volumeOptions: &{CapacityKB:2097152 Tags:map[kubernetes.io/created-for/pvc/namespace:default kubernetes.io/created-for/pvc/name:pvcsc001 kubernetes.io/created-for/pv/name:pvc-e6826590-4cb5-11e8-ab1c-0050568a3505] Name:kubernetes-dynamic-pvc-e6826590-4cb5-11e8-ab1c-0050568a3505 DiskFormat:thin Datastore:vsanDatastore VSANStorageProfileData: StoragePolicyName: StoragePolicyID: SCSIControllerType:}
Apr 30 21:00:56 XXXXXXX-master-k8-01 kube-system_kube-controller-manager-xxxxx-master-k8-01[14960]: E0430 21:00:56.580734       1 vsphere.go:484] cannot find vcServer "<vcenter-dnsname>" in cache. VC not found!!!
Apr 30 21:00:56 XXXXXX-master-k8-01 kube-system_kube-controller-manager-xxxxxx-master-k8-01[14960]: I0430 21:00:56.580808       1 pv_controller.go:1379] failed to provision volume for claim "default/pvcsc001" with StorageClass "fast": Cannot find node "<vcenter-dnsname>" in vsphere configuration map`

Below is the configured vsphere.conf file 
`[Global]
####properties in this section will be used for all specified vCenters unless overriden in VirtualCenter section.

user = "<user-name>"
password = "<password>"
port = "443" #Optional
insecure-flag = "1" #set to 1 if the vCenter uses a self-signed cert
datacenters = "<DC-name>"

[VirtualCenter "1.2.3.4"]
#####Override specific properties for this Virtual Center.
        user = "<user-name>"
        password = "<password>"
        # port, insecure-flag, datacenters will be used from Global section.

[VirtualCenter "1.2.3.5"]
#####Override specific properties for this Virtual Center.
        port = "448"
        insecure-flag = "0"
        # user, password, datacenters will be used from Global section.

[Workspace]
#####Specify properties which will be used for various vSphere Cloud Provider functionality.
####e.g. Dynamic provisioing, Storage Profile Based Volume provisioning etc.
        server = "<IP>"
        datacenter = "<name>"
        folder = "/<dc-name>/vm/kubernetes/"
        default-datastore = "vsanDatastore" #Datastore to use for provisioning volumes using storage classes/dynamic provisioning
####        resourcepool-path = "<cluster-name>/Resources/K8" # Used fordummy VM creation. Optional

[Disk]
        scsicontrollertype = pvscsi

[Network]
        public-network = "VM Cloud Network"`

**What you expected to happen**: able to create volume 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.7
- Cloud provider or hardware configuration: Vmware
- OS (e.g. from /etc/os-release): "Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
- Kernel (e.g. `uname -a`):Linux us06000c3-datanode-001 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by divyenpatel** [comment]
provided sample vsphere.conf file to @s0komma

**Comment by divyenpatel** [comment]
@s0komma does not have read role set on the user specified in the vsphere.conf file.

Please refer.
https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/vcp-roles.html#minimal-set-of-vsphere-rolesprivileges-required-for-dynamic-persistent-volume-provisioning-with-storage-policy-based-volume-placement

**Comment by s0komma** [comment]
updated the permission to make sure that user has Propagate to Children is set to true at least for Read-only role — beginning from vcenter level. Also updated the new vsphere.conf file 
`[Global]
user = "Administrator1@vsphere.local"
password = "****"
port = "443"insecure-flag = "1"
datacenters = "DCname"
[VirtualCenter "IP/FQDN"]
[Workspace]
server = "IP/FQDN"
datacenter = "DC"
default-datastore="Datastore"
resourcepool-path="cluster/Resources/<pool-name>"
folder = "<folder-name>"
[Disk]
scsicontrollertype = pvscsi
[Network]
public-network = "Network"`

after this we are able to create and delete volumes using dynamic provisioning. Thank you @divyenpatel  for all the guidance and support.
