### ISSUE TITLE
kubelet.service: Main process exited, code=exited after 

### ISSUE THREAD

**Issue by boeyeb** [vmware/kubernetes#483]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
Sample vsphere.conf

[Global]
        user = "********"
        password = "********"
        port = "443"
        insecure-flag = "1"
        datacenters = "******** - ********"

[Workspace]
        server = "********"
        datacenter = "********
        folder = "ctk8s"
        default-datastore = "********"
        resourcepool-path = "*/Resources"

[Disk]
        scsicontrollertype = pvscsi

[Network]
        public-network = "SC - VM Network"

kubelet.service: Main process exited after adding flags to controller-manager, API server and Kubelet
May 03 19:08:37 ctk8s-master kubelet[29547]: I0503 19:08:37.299886   29547 feature_gate.go:226] feature gates: &{{} map[]}
May 03 19:08:37 ctk8s-master kubelet[29547]: W0503 19:08:37.319427   29547 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection cleanup.
May 03 19:08:37 ctk8s-master kubelet[29547]: I0503 19:08:37.319579   29547 server.go:376] Version: v1.10.2
May 03 19:08:37 ctk8s-master kubelet[29547]: I0503 19:08:37.319735   29547 feature_gate.go:226] feature gates: &{{} map[]}
May 03 19:08:37 ctk8s-master kubelet[29547]: E0503 19:08:37.320217   29547 vsphere.go:264] Global.WorkingDir is empty!
May 03 19:08:37 ctk8s-master kubelet[29547]: F0503 19:08:37.320353   29547 server.go:233] failed to run Kubelet: could not init cloud provider "vsphere": Global.WorkingDir is empty!
**What you expected to happen**:
kubelet.service:  not crashing

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:10:24Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: vCenter
- OS (e.g. from /etc/os-release): coreos
- Kernel (e.g. `uname -a`):Linux ctk8s-master 4.14.32-coreos #1 SMP Tue Apr 3 05:21:26 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz GenuineIntel GNU/Linux
- Install tools: kubeadm
- Others:

**Comment by abrarshivani** [comment]
@boeyeb Global.WorkingDir is missing in vsphere.conf file. 
Following is the right format for provided conf file:
```
[Global]
user = ""
password = ""
port = "443"
insecure-flag = "1"
datacenters = "******** - ********"

[VirtualCenter ""]

[Workspace]
server = ""
datacenter = "
folder = "ctk8s"
default-datastore = "********"
resourcepool-path = "*/Resources"
```

**Comment by boeyeb** [comment]
Hi Abrar,

Doesn't work.
new error

May 08 08:07:46 ctk8s-master kubelet[18683]: F0508 08:07:46.695430   18683 server.go:233] failed to run Kubelet: could not init cloud provider "vsphere": 9:16: empty subsection name

Thx

**Comment by abrarshivani** [comment]
@boeyeb This error has occurred because server ip is missing in conf file.
```
[Global]
user = ""
password = ""
port = "443"
insecure-flag = "1"
datacenters = "******** - ********"

[VirtualCenter ""] <--- Add server address in quotes here.

[Workspace]
server = ""
datacenter = "
folder = "ctk8s"
default-datastore = "********"
resourcepool-path = "*/Resources"
```

**Comment by abrarshivani** [comment]
@boeyeb Can we close this issue now?
