### ISSUE TITLE
Kubernetes 1.10.2 Nodes marked NotReady when VCP is installed

### ISSUE THREAD

**Issue by dkirrane** [vmware/kubernetes#485]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

/kind bug

**What happened**:
I created a cluster with kubeadm `1.10.2` ( 1 master & 3 worker nodes)
`kubectl get nodes` show nodes marked as `Ready`

I then installed  VCP with as [per instructions](https://github.com/vmware/kubernetes/blob/enable-vcp-uxi/README.md)

**What you expected to happen**:
Some Nodes become `NotReady`

```
kubectl get nodes
NAME           STATUS     ROLES     AGE       VERSION
master1-prod   Ready      <none>    7m        v1.10.2
minion1-prod   NotReady   <none>    7m        v1.10.2
minion2-prod   Ready      <none>    7m        v1.10.2
minion3-prod   NotReady   <none>    7m        v1.10.2
```

But VcpSummary shows nodes successfully configured:
`"nodes_sucessfully_configured": "4",`

The only thing I can see when I describe the NotReady node is
```
 Ready            False   Tue, 15 May 2018 14:16:06 +0100   Tue, 15 May 2018 14:06:26 +0100   KubeletNotReady              container runtime is down
```
I checked status on the NotReady nodes
```
systemctl status kubelet
systemctl status docker
```
Both kubelet and docker are `active (running)`
Kubelet on the node shows
```
journalctl -u kubelet -n 100
May 15 14:12:52 minion1-prod kubelet[3021]: I0515 14:12:52.277345    3021 kubelet.go:1794] skipping pod synchronization - [container runtime is down]
```

**How to reproduce it (as minimally and precisely as possible)**:
```
kubeadm init with flannel
kubeadmin join 3 other nodes
kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f vcp_namespace_account_and_roles.yaml
kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f vcp_secret.yaml
kubectl --kubeconfig=/etc/kubernetes/admin.conf create -f enable-vsphere-cloud-provider.yaml
```

**Anything else we need to know?**:
```
 kubectl get pods --namespace=vmware
NAME                   READY     STATUS    RESTARTS   AGE
vcp-daementset-blbw2   1/1       Running   0          3m
vcp-daementset-fkl84   1/1       Running   0          3m
vcp-daementset-mqzhw   1/1       Running   0          3m
vcp-daementset-q6bzl   1/1       Running   0          3m
vcp-manager            1/1       Running   0          3m
```

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.10.2`
- Cloud provider or hardware configuration: vCenter 6.5
- OS (e.g. from /etc/os-release):  CentOS Linux 7
- Kernel (e.g. `uname -a`): `Linux master1-prod 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: 
- Others:

**Comment by divyenpatel** [comment]
@dkirrane Can you check if kubelet is up and running on `minion1-prod` and `minion3-prod`. 
After configuring nodes for vSphere Cloud Provider, script restart kubelet on nodes. 

See
https://github.com/vmware/kubernetes/blob/enable-vcp-uxi/enable-vcp-image/enable-vcp-scripts/daemonset_pod.sh#L375

Following script is getting executed in the last phase of configuration.
```
echo '#!/bin/sh
systemctl daemon-reload
systemctl restart ${K8S_SECRET_KUBERNETES_KUBELET_SERVICE_NAME}
```

Can you share log of daementset pods running on `minion1-prod` and `minion3-prod`.

**Comment by dkirrane** [comment]
ok i've tried to recreate cluster again with vcp. Now I'm hitting ImageInspectError on `cnastorage/enablevcp:v2`

```
kubectl --namespace=vmware describe pod vcp-manager


Events:
  Type     Reason                 Age               From                   Message
  ----     ------                 ----              ----                   -------
  Normal   SuccessfulMountVolume  9m                kubelet, minion2-prod  MountVolume.SetUp succeeded for volume "secret-volume"
  Normal   SuccessfulMountVolume  9m                kubelet, minion2-prod  MountVolume.SetUp succeeded for volume "default-token-zmjkx"
  Normal   Scheduled              9m                default-scheduler      Successfully assigned vcp-manager to minion2-prod
  Warning  InspectFailed          7m (x11 over 9m)  kubelet, minion2-prod  Failed to inspect image "cnastorage/enablevcp:v2": rpc error: code = Unknown desc = Error response from daemon: readlink /var/lib/docker/overlay2: invalid argument
  Warning  Failed                 4m (x24 over 9m)  kubelet, minion2-prod  Error: ImageInspectError
```

**Comment by embano1** [comment]
@dkirrane IIRC we also discussed this on Slack and your finding was that a recreate of the cluster/VM resolved the issue (just can't find the chat anymore, too many Slack channels).

Could you please confirm?

**Comment by dkirrane** [comment]
@embano1 I resolved the ImageInspectError by using devicemapper instead of overlay2 storage driver in Docker.
However, I couldn't get VCP working with enable-vcp-uxi, even after reboot. 
I switched back to manually setting the flags etc in kubeadm, apiserver and controller manager. This works

**Comment by embano1** [comment]
Thx, is it ok to close this issue then?

**Comment by dkirrane** [comment]
@embano1 sure
