### ISSUE TITLE
Fix locating resporce-pool specified in the vsphere.conf file

### ISSUE THREAD

**Issue by mansi-a** [vmware/kubernetes#493]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
We need to use `resourcepool-path` when we use SPBM policies with dynamic provisioning in vSphere Cloud Provider or the PVC provisioning fails with error
`Warning  ProvisioningFailed  3m (x61 over 18m)  persistentvolume-controller  Failed to provision volume with StorageClass "xxx": default compute resource resolves to multiple instances, please specify`

`resourcepool-path is the path to resource pool where dummy VMs for Storage Profile Based volume provisioning should be created. It is optional parameter.`

If admin changes the name of their VC cluster with above configuration, dynamic provisioning breaks.
`Failed to provision volume with StorageClass "xxx": compute resource '/datacenter-xxx/host/cluster-xxx' not found.`

Using an identifier based on MoID instead of path for compute resource would be more stable.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.2
- Cloud provider or hardware configuration: vsphere
- OS (e.g. from /etc/os-release):
NAME="VMware Photon OS"
VERSION="2.0"
ID=photon
VERSION_ID=2.0
PRETTY_NAME="VMware Photon OS/Linux"
ANSI_COLOR="1;34"
HOME_URL="https://vmware.github.io/photon/"
BUG_REPORT_URL="https://github.com/vmware/photon/issues"
- Kernel (e.g. `uname -a`):
Linux 8db8581d738e41c49ec61003ea3e8f51 4.9.101-1.ph2-esx #1-photon SMP Tue May 22 01:42:59 UTC 2018 x86_64 Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz GenuineIntel GNU/Linux
- Install tools:
- Others:

**Comment by divyenpatel** [comment]
We have a bug here. See the following code.
 
https://github.com/kubernetes/kubernetes/blob/master/pkg/cloudprovider/providers/vsphere/vclib/datacenter.go#L158:23
 
Call trace.
func (vs *VSphere) CreateVolume(volumeOptions *vclib.VolumeOptions) (canonicalVolumePath string, err error)
    vmOptions, err = vs.setVMOptions(ctx, dc, vs.cfg.Workspace.ResourcePoolPath)
      resourcePool, err := dc.GetResourcePool(ctx, resourcePoolPath)
 
 
Code block where fix needs to be made.

```
if computePath == "" {
     computeResource, err = finder.DefaultComputeResource(ctx)
} else {
     computeResource, err = finder.ComputeResource(ctx, computePath)
}
```
 
Here method accept the `computePath` which is actually a `resourcepool-path` set in the vsphere.conf file.
Look up is being made using `finder.DefaultComputeResource(ctx)` and `finder.ComputeResource(ctx, computePath)`, which is not correct.
 
This can be resolved with using correct method - func (f *Finder) ResourcePoolOrDefault(ctx context.Context, path string) (*object.ResourcePool, error)
https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/vmware/govmomi/find/finder.go#L867

I will make above change. and try to cherry pick in older releases.

Regarding asking users to put `MoID` in the `vsphere.conf` file seems developer friendly, but not administrator friendly.

**Comment by divyenpatel** [comment]
Closing this issue. PR merged to master branch. I will cherry pick this change to other release branches.
