### ISSUE TITLE
Setup a nightly CI job

### ISSUE THREAD

**Issue by kerneltime** [vmware/kubernetes#50]
# Kind of tests
Should tests be:

- [x] Part of k8s repo e2e tests

- [ ] ~~Scripts sitting outside of k8s repo~~

# Where to host the tests
Should tests be (not mutually exclusive):

- [ ] Run as part of a CI

- [ ] Run integrated into the k8s testing framework

- [ ] Run manually on test beds

**Comment by tusharnt** [comment]
Define a nightly job to achieve the following - 
0.  Identify how and where to schedule nightly job
1.  Compile k8s master branch
2.  Deploy VSAN testbed on Nimbus 
3.  Deploy k8s cluster using ToT kube-anywhere using k8s binaries from step#1
4.  Run vSphere end to end tests

**Comment by abrarshivani** [comment]
This can be done once this (https://github.com/kubernetes/kubernetes-anywhere/pull/326) is merged

**Comment by divyenpatel** [comment]
Infrastructure setup

- [ ] Install and configure jenkins master node. - <a href='http://cna-storage-jenkins.eng.vmware.com:8080/'>http://cna-storage-jenkins.eng.vmware.com:8080/</a>

- [ ] Install and configure jenkins worker nodes - Use Photon VMs

- [ ] Create docker image to use for executing build script - CI container will be launched in privileged mode with this image. Expose docker socket from jenkins worker node to this container using bind-mounting with the "-v" flag.

- [ ] Create build script to build kubernetes-anywhere, kubernetes and execution of e2e test cases on a predeployed testbed

- [ ]  Nightly build for Kubernetes Master -  use latest stable master build available at https://storage.googleapis.com/kubernetes-release-dev/ci/latest-green.txt - Done <a href="http://cna-storage-jenkins.eng.vmware.com:8080/job/k8s-release-dev-ci-latest/">http://cna-storage-jenkins.eng.vmware.com:8080/job/k8s-release-dev-ci-latest/</a>

- [ ] Nightly build for Kubernetes release 1.5 branch - Done <a href="http://cna-storage-jenkins.eng.vmware.com:8080/job/k8s-release-1.5-validation/">http://cna-storage-jenkins.eng.vmware.com:8080/job/k8s-release-1.5-validation/</a>

- [ ] Nightly build for Kubernetes release 1.6 branch 
- [ ] Nightly build for Kubernetes release 1.7 branch
- [ ] build job for tagged release validation - done <a href="http://cna-storage-jenkins.eng.vmware.com:8080/job/k8s-tagged-release-validation/">http://cna-storage-jenkins.eng.vmware.com:8080/job/k8s-tagged-release-validation/</a>
