### ISSUE TITLE
vSphere Cloud Provider currently support RWO access does that mean, recreating a pod on new vm cannot access previously used volume?

### ISSUE THREAD

**Issue by GajaHebbar** [vmware/kubernetes#507]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**I have a cluster with a master and 3 worker node, where I have created a pod(worker-1) which is say database image, and there is a pvc/sc attached to it. if for some reason the pod get killed and recreated on different vm(worker-2), can the pod which was created on worker-1 which accessed vloume and stored data be accessed by same pod on worker-2 when it gets recreated? **:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version Kubernetes version Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration vmware
- OS "Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
- Kernel Linux flexmaster191 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by divyenpatel** [comment]
@GajaHebbar 

VCP supports `RWO` mode means, Volume is accessible to pods co-located on same worker Node VM. Volume cannot be attached to multiple Node VMs at the same time.

When POD is re-created on the new Node. Disk is detached from the previous node VM and gets attached to the new Node VM.

**Comment by GajaHebbar** [comment]
@divyenpatel  Thank you for the clarification

**Comment by GajaHebbar** [comment]
@divyenpatel One quick question on vsphere.conf network
![network](https://user-images.githubusercontent.com/37359075/45750492-e3216680-bc2c-11e8-88ca-d77022b5a2a9.JPG)
my network is as shown as above, and I want to use network 10-133-(84,85,86,87)-X

so in vsphere.conf network should be mentioned as bellow? Is that correct?

[Network]
public-network = "Pune_Shared_Cluster1_Public_Network/10-133-(84,85,86,87)-X"

**Comment by divyenpatel** [comment]
@GajaHebbar We do not need to specify network folder with the network name.

Following should be good.
```
[Network]
public-network = "10-133-(84,85,86,87)-X"
```

See how it is used.
https://github.com/kubernetes/kubernetes/blob/e3dbad3211831b770f98ea4d5e24235dc0e038e3/pkg/cloudprovider/providers/vsphere/vsphere.go#L647-L665


Can you verify `Addresses` set on the Node?

```
kubectl describe node node-name
.
.
Addresses:
  ExternalIP:  1.1.1.1
  InternalIP:  1.1.1.1
  Hostname:    kubernetes-master
.
.
```

**Comment by GajaHebbar** [comment]
Ok, so for any level of folder for network need not to be specified for public-network.

These are the addresses for 1 master and 2 worker node.

Addresses:
  ExternalIP:  10.133.85.191
  InternalIP:  10.133.85.191
  Hostname:    flexmaster191

Addresses:
  ExternalIP:  10.133.85.192
  InternalIP:  10.133.85.192
  Hostname:    flexworker1

Addresses:
  ExternalIP:  10.133.85.193
  InternalIP:  10.133.85.193
  Hostname:    flexworker2

As per your information these look correct. Please confirm

**Comment by divyenpatel** [comment]
Yes looks correct to me. Node IP addresses (10.133.85.*) looks belonging to `10-133-(84,85,86,87)-X` network.

**Comment by GajaHebbar** [comment]
Thank you

**Comment by GajaHebbar** [comment]
@divyenpatel  So for now we don't have a support to RWM(ReadWriteMany) is that correct. In that case is this planned for future?

**Comment by divyenpatel** [comment]
@GajaHebbar Yes in current releases we do not have support for  `ReadWriteMany`. We are working on adding this support in future releases. 

Please subscribe the issue: https://github.com/vmware/kubernetes/issues/306 to get an update on this feature request.
