### ISSUE TITLE
Validate 1.4.8 vSphere Cloud Provider

### ISSUE THREAD

**Issue by kerneltime** [vmware/kubernetes#54]
- [x] Check for regression

- [x] Check for fsgroup fix https://github.com/kubernetes/kubernetes/pull/38655

**Comment by kerneltime** [comment]
Update the official documentation  for k8s and k8s-anywhere

**Comment by divyenpatel** [comment]
Verified fsGroup fix. Executed all automated end to end test cases and performed manual test verification. All tests passed. Will post PR to update documentation.
