### ISSUE TITLE
Update existing e2e kubernetes test cases to run on vSphere provider

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#56]
Update following e2e Test cases to run on vSphere Provider.

- test/e2e/persistent_volumes.go
- test/e2e/volume_provisioning.go
- test/e2e/volumes.go

**Comment by divyenpatel** [comment]
PR: https://github.com/vmware/kubernetes/pull/55

**Comment by tusharnt** [comment]
6 more test cases needs to be ported.

**Comment by divyenpatel** [comment]
- [ ] PV/PVC - Static Provisioning - Deleting a PVC before the pod and expect the pod to succeed in unmounting and detaching PD on delete - Merged https://github.com/kubernetes/kubernetes/pull/40756

- [ ] Deleting the PV before the pod does not cause pod deletion to fail. Expect the pod to succeed in unmounting and detaching PD on delete - Merged https://github.com/kubernetes/kubernetes/pull/40756

- [ ] Test dynamic provisioning using StorageClass and PVC with dynamic provisioning and alpha dynamic provisioning annotations - Merged https://github.com/kubernetes/kubernetes/pull/40756

- [ ] Test to verify volume data is persisted across life cycle of a pod. This test also verifies requested FS Group is set on the mounted volume. - Merged https://github.com/kubernetes/kubernetes/pull/40756

- [ ]  Disrupted kubelet - Test to verify that volume mounted via PVC remains accessible after kubelet restart

- [ ] Test to verify When a pod is deleted while the kubelet is down, the mounted volume is unmounted successfully.

- [ ] test to verify that deleting the Namespace of a PVC and Pod causes the successful detach of Persistent Disk 

- [ ] Attach/Detach controller - If a node with a vsphere volume attached is deleted (before the volume is detached), subsequent attempts by the attach/detach controller to detach it should not fail.

- [ ] Attach/Detach controller - If API object representing a node is deleted with a vsphere volume still attached to that node, subsequent attempts by the attach/detach controller to detach it should not fail.

**Comment by divyenpatel** [comment]
All tests merged.
