### ISSUE TITLE
Support selection of datastore during dynamic provisioning

### ISSUE THREAD

**Issue by kerneltime** [vmware/kubernetes#58]
Currently datastore selection cannot be passed in the storage class specification and is set once during install. We need to add the ability to select a datastore.

**Comment by BaluDontu** [comment]
This is tracked in PR - https://github.com/kubernetes/kubernetes/issues/40558

**Comment by tusharnt** [comment]
PR for master branch is out for review. Fix needs to be cherry picked for 1.5.x.
