### ISSUE TITLE
Add missing e2e tests

### ISSUE THREAD

**Issue by kerneltime** [vmware/kubernetes#64]
Tests defined here and other new tests not covered by existing e2e test should be added.

**Comment by divyenpatel** [comment]
- [ ] PV/PVC - Reclaiming Policy - Verify persistent volume should be deleted when reclaimPolicy on the PV is set to delete and associated claim is deleted - Merged https://github.com/kubernetes/kubernetes/pull/40756

- [ ] PV/PVC - Reclaiming Policy - Verify persistent volume should be retained when reclaimPolicy on the PV is set to retain and associated claim is deleted - Merged https://github.com/kubernetes/kubernetes/pull/40756

- [ ] PV/PVC - With Label Selector - Verify volume with the matching label is bounded with the PVC. This is function test for Selector-Label Volume Binding Feature. - Merged https://github.com/kubernetes/kubernetes/pull/40756

- [ ] Basic volume plugin - With Node Label Selector - Test Back-to-back pod creation/deletion with the same volume source on the same worker node - Merged https://github.com/kubernetes/kubernetes/pull/40756

- [ ] Basic volume plugin - With Node Label Selector - Test Back-to-back pod creation/deletion with the same volume source attach/detach to different worker nodes - Merged https://github.com/kubernetes/kubernetes/pull/40756

- [ ] PV/PVC - StorageClass - Diskformat Verification - Verify diskformat specified in storage-class is being honored while volume creation. - In Review - https://github.com/kubernetes/kubernetes/pull/41239

- [ ] Basic volume plugin - Test multiple volumes from same datastore within the same POD

- [ ] Basic volume plugin - Test multiple volumes from different datastores within the same POD

- [ ] Basic volume plugin - With Node Label Selector - Test Back-to-back pod creation/deletion with different volume sources on the same worker node

- [ ] Basic volume plugin - Service comprising multiple PODs where each POD uses his own volume

- [ ] Disk Ops Strome - PV/PVC and Volume Plugin - Test creating POD with many volumes (30 Volumes) and verify none attach call fails.

- [ ] Basic volume plugin - mark node as un-schedulable - Test pod provisioning with same volume on different worker nodes. Mark node as unschedulable on which first pod is created. Use API for kubectl cordon / kubectl uncordon

- [ ] Basic volume plugin - Filesystem type test - Verify volume attached to the POD is mounted on the container with correct file system.

- [ ] PV/PVC tests - PV AccessMode Test - Only "RWO" is supported - Verify PV created using AccessMode RWO can only be mounted to one node.

- [ ] End to End App Deployment Using - Guest Book PVC - Automate deployment of app using YAMLs located at https://github.com/vmware/vmware-private-kubernetes-collaboration/tree/master/CloudProviders/demo/guestbook-pvc - Create and Delete Deployment twice and verify previously written data is accessible.

- [ ] End to End App Deployment Using - Guest Book StorageClass - Automate deployment of app using YAMLs located at https://github.com/vmware/vmware-private-kubernetes-collaboration/tree/master/CloudProviders/demo/guestbook-storageclass - Create and Delete Deployment twice and verify no previously written data should be available.

- [ ] End to End App Deployment Using -GuestBook Volumes - Automate deployment of app using YAMLs located at - https://github.com/vmware/vmware-private-kubernetes-collaboration/tree/master/CloudProviders/demo/guestbook-volumes - Create and Delete Deployment twice and verify previously written data is accessible.

**Comment by BaluDontu** [comment]
VSAN policy

Create multiple PVC's with VSAN policies and make sure all PVC's are bounded and all the disks are detached from dummy VM. *
Host failure of the dummy VM in case of vSphere HA.
Will dummyVM be moved onto other available hosts and will continue to process incoming PVC's.
Write test case for using datastore parameter on storage class.
Test for accessible/non-accessible datastores.
Create a kubernetes cluster on non-VSAN datastores. Create a PVC with VSAN policy parameters on a VSAN datastore. Make sure PVC is bounded. 
Delete/Remove a dummy VM from VC inventory. Now create a PVC with VSAN policy. Make sure the dummy VM is created again on the VC

ESX host failure - VSAN, vSphere HA
Host failure in a way that node becomes inaccessible. Power off hosts in such a way VM disk is not accessible as the hosts that contains a copy of VM disk is powered off. (Shangai team case)

Node Power Off/Power On Test 
Does POD restart successfully with volume accessible on new node?
Power on the powered off node and make sure it is running. Make sure the disk is detached from powered off node.

**Comment by BaluDontu** [comment]
All the missing test cases are tracked as part of this EPIC - https://github.com/vmware/kubernetes/issues/282. Closing this issue.
