### ISSUE TITLE
vSphere Cloud provider: wrong vm path when using multiple working-dir #40084

### ISSUE THREAD

**Issue by kerneltime** [vmware/kubernetes#65]
Track https://github.com/kubernetes/kubernetes/issues/40084

**Comment by tusharnt** [comment]
Still waiting to hear back from customer.

**Comment by tusharnt** [comment]
@BaluDontu Can this be closed?

**Comment by prashima** [comment]
cc @BaluDontu 
Closing this in absence of any communication from customer.
