### ISSUE TITLE
Limit users from creating vmdks using storage class

### ISSUE THREAD

**Issue by abrarshivani** [vmware/kubernetes#76]
Currently, there is no quota for users for creating vmdk. Hence, there should be some way to limit users from creating vmdk.

**Comment by kerneltime** [comment]
https://kubernetes.io/docs/admin/resourcequota/

**Comment by divyenpatel** [comment]
looks like this feature is already supported on vsphere cloud provider.
Verified this on the build : v1.6.3-beta.0.30+a3d70e674b6d49

Created ResourceQuota to limit 10 claims or 40Gi storage
```

$ cat resource_quota.yaml 
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
spec:
  hard:
    persistentvolumeclaims: "10"
    requests.storage: "40Gi"

$ kubectl create -f resource_quota.yaml 
resourcequota "quota" created
```

Created two PVC request one with 2Gi and another with 38Gi storage request. PVs got provisioned.

```
$ kubectl get pvc
NAME         STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
thinclaim    Bound     pvc-e756ba02-2fba-11e7-9055-005056b7eed4   2Gi        RWO           16s
thinclaim2   Bound     pvc-e9d54356-2fba-11e7-9055-005056b7eed4   38Gi       RWO           11s
```

resource usage got updated as below.

```
$ kubectl describe quota
Name:			quota
Namespace:		default
Resource		Used	Hard
--------		----	----
persistentvolumeclaims	2	10
requests.storage	      40Gi	40Gi
```

**when tried to provision one more pv of 2Gi capacity, request got Forbidden with following error message.**

```
$ kubectl create -f thin_pvc3.yaml 
Error from server (Forbidden): error when creating "thin_pvc3.yaml": persistentvolumeclaims "thinclaim3" is forbidden: exceeded quota: quota, requested: requests.storage=2Gi, used: requests.storage=40Gi, limited: requests.storage=40Gi
```

cc: @BaluDontu

**Comment by BaluDontu** [comment]
Is resource quota w.r.t namespace or does it apply to whole cluster?

**Comment by divyenpatel** [comment]
`ResourceQuota` is set per namespace

**Comment by BaluDontu** [comment]
@abrarshivani : Let us know if you have any comments. Otherwise we can close this.
