### ISSUE TITLE
Add uuid support  to kubernetes-anywhere

### ISSUE THREAD

**Issue by kerneltime** [vmware/kubernetes#82]
https://github.com/kubernetes/kubernetes-anywhere/issues/329

**Comment by pdhamdhere** [comment]
Why is it P0? kube-anywhere uses Photon OS which has unique bios ID so should work without any change. Correct? @BaluDontu

**Comment by BaluDontu** [comment]
True, but the question over here is whether the UUID is accessible within the kubelet container. The UUID is present in /sys/devices/virtual/dmi/id/product_uuid. 

I see that /sys directory is already mounted inside the kubelet container. So this UUID would be accessible to kubelet. 

However, will verify once by testing it with master kubernetes branch which has the latest change.

**Comment by BaluDontu** [comment]
No longer required. The cloud provider has logic to query it internally on the node.
