### ISSUE TITLE
White paper on security and cluster isolation for kubernetes.

### ISSUE THREAD

**Issue by kerneltime** [vmware/kubernetes#86]

**Comment by kerneltime** [comment]
Ran info 

- [ ] Configuration issues

- [ ] Disk in use

- [ ] UUID issue even though enableUUID seems to be set
```
{"log":"I0213 09:48:43.502621       1 operation_executor.go:620] AttachVolume.Attach succeeded for volume \"kubernetes.io/vsphere-volume/[netapp01ads02] k8s/myDisk\" (spec.Na
me: \"test-volume\") from node \"k8s.minionpp-01\".\n","stream":"stderr","time":"2017-02-13T09:48:43.502834346Z"}
{"log":"I0213 09:48:43.599644       1 node_status_updater.go:135] Updating status for node \"k8s.minionpp-01\" succeeded. patchBytes: \"{\\\"status\\\":{\\\"volumesAtt
ached\\\":[{\\\"devicePath\\\":\\\"/dev/disk/by-id/wwn-0x6000c2931824b17ebd31f2dc365f0d67\\\",\\\"name\\\":\\\"kubernetes.io/vsphere-volume/[netapp01ads02] k8s/myDisk\\\"}]}}
\" VolumesAttached: [{kubernetes.io/vsphere-volume/[netapp01ads02] k8s/myDisk /dev/disk/by-id/wwn-0x6000c2931824b17ebd31f2dc365f0d67}]\n","stream":"stderr","time":"2017-02-13
T09:48:43.599797118Z"}
{"log":"E0213 09:48:46.750024       1 vsphere.go:1062] disk uuid not found for [netapp01ads02] k8s/myDisk. err: No disk UUID found\n","stream":"stderr","time":"2017-02-13T09:
48:46.750250047Z"}
{"log":"E0213 09:48:46.750107       1 vsphere.go:1044] Failed to check whether disk is attached. err: No disk UUID found\n","stream":"stderr","time":"2017-02-13T09:48:46.7502
7874Z"}
```

**Comment by cvauvarin** [comment]
@kerneltime the problem was a permission issue on the vCenter. Do you think it is possible to add  in the documentation a list of permissions that are needed?

**Comment by kerneltime** [comment]
@cvauvarin yes of course, can you elaborate on the permissions problem? The last you mentioned that the disk was attached to the VM, I am not sure why permissions made a difference.

**Comment by cvauvarin** [comment]
Yes the disk was attached to the VM but the `kube-controller` could not get the UUID of the disk. What I did is that I used another user with full permissions on the vCenter and it worked without any issue. Then we tried to add some permissions to the other user to make it worked. 

Here is the list of the permissions we applied :
- Datastore :
  - Allocate space
  - Browse datastore
  - Low level file operations
  - Update virtual machines files
  - Update virtual machnes metadata
- Virtual machine
  - Configuration
    - Add existing disk
    - Add new disk
    - Remove disk

Don't think it was a problem of reading the uuid, do you think it can be a problem writing some metadata ?

**Comment by kerneltime** [comment]
Thank you for the additional info.

**Comment by tusharnt** [comment]
This issue tracks the list of privileges the user needs to specify in vSphere UI in order to configure vSphere cloud provider.

**Comment by kerneltime** [comment]
Relevant https://bugzilla.eng.vmware.com/show_bug.cgi?id=1791819

**Comment by kerneltime** [comment]
A hacky reference between API spec and UI spec 
[auth-privs.txt](https://github.com/vmware/kubernetes/files/798131/auth-privs.txt)

**Comment by kerneltime** [comment]
Partial list
```
Privileges

FindByIp 	   => System.View
MakeDirectory => Datastore.FileManagement #  https://bugzilla.eng.vmware.com/show_bug.cgi?id=1791819
```

**Comment by kerneltime** [comment]
The goal here is to have a white paper that explains what is possible to isolate the credentials used in kubernetes and what is the level of isolation achieved and gaps that a customer should be aware about.

**Comment by divyenpatel** [comment]
Updated Getting Started Guide with minimal set of privileges required for vSphere Cloud Provider
https://github.com/kubernetes/kubernetes.github.io/pull/2989

**Comment by divyenpatel** [comment]
Updated k8s-anywhere prerequisites section with privileges required for Kubernetes-Anywhere.
https://github.com/kubernetes/kubernetes-anywhere/pull/360

**Comment by divyenpatel** [comment]
Updated documentation with required set of roles and permissions required for Kubernetes vsphere cloud provider.
