### ISSUE TITLE
kubernetes-anywhere: 2 Clusters in same resource pool

### ISSUE THREAD

**Issue by kerneltime** [vmware/kubernetes#92]
tracking https://github.com/kubernetes/kubernetes-anywhere/issues/296

**Comment by divyenpatel** [comment]
PR: https://github.com/kubernetes/kubernetes-anywhere/pull/437 fixes this issue.
To deploy multiple cluster in the same resource pool, specify different cluster name for each deployment. Node VM names are now prefixed with Kubernetes Cluster name, which allows deploying multiple clusters in the same resource pool.
