### ISSUE TITLE
kubernetes-anywhere: Silent failures

### ISSUE THREAD

**Issue by kerneltime** [vmware/kubernetes#93]
Install can fail silently without notifying the user.
Tracking issue https://github.com/kubernetes/kubernetes-anywhere/issues/299

**Comment by luomiao** [comment]
PR out for review:
https://github.com/kubernetes/kubernetes-anywhere/pull/347

But maybe we want to add a timeout handling into the validation script too.
I would like to put this into another PR since it will affect other providers.

**Comment by luomiao** [comment]
PR merged.
