### ISSUE TITLE
POD creation failed on 1.5.3  build with "Unable to mount volumes for pod "

### ISSUE THREAD

**Issue by divyenpatel** [vmware/kubernetes#96]
POD creation failed on 1.5.3 branch build with "Unable to mount volumes "
POD spec contains  fsGroup and seLinuxOptions as below. 

```
    securityContext:
      fsGroup: 1234
      seLinuxOptions:
        level: "s0:c0,c1"
```

This test is  passing on 1.4.8 setup.

 ```
kubectl describe pods -n e2e-tests-volume-bj3bt
Name:		vsphere-injector
Namespace:	e2e-tests-volume-bj3bt
Node:		node1/10.162.47.213
Start Time:	Tue, 14 Feb 2017 12:50:06 -0800
Labels:		role=vsphere-injector
Status:		Pending
IP:		
Controllers:	<none>
Containers:
  vsphere-injector:
    Container ID:	
    Image:		gcr.io/google_containers/busybox:1.24
    Image ID:		
    Port:		
    Command:
      /bin/sh
    Args:
      -c
      echo 'Hello from vSphere from namespace e2e-tests-volume-bj3bt' > /mnt/index.html && chmod o+rX /mnt /mnt/index.html
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Volume Mounts:
      /mnt from vsphere-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-4xqtg (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  vsphere-volume:
    Type:	vSphereVolume (a Persistent Disk resource in vSphere)
    VolumePath:	[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk
    FSType:	ext4
  default-token-4xqtg:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-4xqtg
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  2m		2m		1	{default-scheduler }			Normal		Scheduled	Successfully assigned vsphere-injector to node1
  20s		20s		1	{kubelet node1}				Warning		FailedMount	Unable to mount volumes for pod "vsphere-injector_e2e-tests-volume-bj3bt(2a38c13d-f2f7-11e6-8412-005056a57341)": timeout expired waiting for volumes to attach/mount for pod "e2e-tests-volume-bj3bt"/"vsphere-injector". list of unattached/unmounted volumes=[vsphere-volume]
  20s		20s		1	{kubelet node1}				Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "e2e-tests-volume-bj3bt"/"vsphere-injector". list of unattached/unmounted volumes=[vsphere-volume]
```

Logs

`
Feb 14 20:50:06 photon-zv1KbtvMG docker[452]: I0214 20:50:06.097487     483 kubelet.go:1781] SyncLoop (ADD, "api"): "vsphere-injector_e2e-tests-volume-bj3bt(2a38c13d-f2f7-11e6-8412-005056a57341)"
Feb 14 20:50:06 photon-zv1KbtvMG docker[452]: I0214 20:50:06.145083     483 reconciler.go:230] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk" (spec.Name: "vsphere-volume") pod "2a38c13d-f2f7-11e6-8412-005056a57341" (UID: "2a38c13d-f2f7-11e6-8412-005056a57341")
Feb 14 20:50:06 photon-zv1KbtvMG docker[452]: E0214 20:50:06.145479     483 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk\"" failed. No retries permitted until 2017-02-14 20:50:06.645104001 +0000 UTC (durationBeforeRetry 500ms). Error: Volume "kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk" (spec.Name: "vsphere-volume") pod "2a38c13d-f2f7-11e6-8412-005056a57341" (UID: "2a38c13d-f2f7-11e6-8412-005056a57341") has not yet been added to the list of VolumesInUse in the node's volume status.

Feb 14 20:50:07 photon-zv1KbtvMG docker[452]: I0214 20:50:07.360293     483 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/b6f77f61-f272-11e6-af98-005056a57341-default-token-ljttl" (spec.Name: "default-token-ljttl") pod "b6f77f61-f272-11e6-af98-005056a57341" (UID: "b6f77f61-f272-11e6-af98-005056a57341").
Feb 14 20:50:07 photon-zv1KbtvMG docker[452]: I0214 20:50:07.658463     483 reconciler.go:230] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk" (spec.Name: "vsphere-volume") pod "2a38c13d-f2f7-11e6-8412-005056a57341" (UID: "2a38c13d-f2f7-11e6-8412-005056a57341")
Feb 14 20:50:07 photon-zv1KbtvMG docker[452]: E0214 20:50:07.659257     483 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk\"" failed. No retries permitted until 2017-02-14 20:50:09.659151257 +0000 UTC (durationBeforeRetry 2s). Error: Volume "kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk" (spec.Name: "vsphere-volume") pod "2a38c13d-f2f7-11e6-8412-005056a57341" (UID: "2a38c13d-f2f7-11e6-8412-005056a57341") has not yet been added to the list of VolumesInUse in the node's volume status.

Feb 14 20:50:13 photon-zv1KbtvMG docker[452]: I0214 20:50:13.415639     483 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/b6f05f02-f272-11e6-af98-005056a57341-default-token-ljttl" (spec.Name: "default-token-ljttl") pod "b6f05f02-f272-11e6-af98-005056a57341" (UID: "b6f05f02-f272-11e6-af98-005056a57341").
Feb 14 20:50:13 photon-zv1KbtvMG docker[452]: I0214 20:50:13.710899     483 reconciler.go:230] VerifyControllerAttachedVolume operation started for volume "kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk" (spec.Name: "vsphere-volume") pod "2a38c13d-f2f7-11e6-8412-005056a57341" (UID: "2a38c13d-f2f7-11e6-8412-005056a57341")
Feb 14 20:50:13 photon-zv1KbtvMG docker[452]: E0214 20:50:13.711696     483 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk\"" failed. No retries permitted until 2017-02-14 20:50:21.71119957 +0000 UTC (durationBeforeRetry 8s). Error: Volume "kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk" (spec.Name: "vsphere-volume") pod "2a38c13d-f2f7-11e6-8412-005056a57341" (UID: "2a38c13d-f2f7-11e6-8412-005056a57341") has not yet been added to the list of VolumesInUse in the node's volume status.

Feb 14 21:00:21 photon-zv1KbtvMG docker[452]: E0214 21:00:21.879894     483 nestedpendingoperations.go:262] Operation for "\"kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk\"" failed. No retries permitted until 2017-02-14 21:00:22.379290859 +0000 UTC (durationBeforeRetry 500ms). Error: MountVolume.WaitForAttach failed for volume "kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk" (spec.Name: "vsphere-volume") pod "2a38c13d-f2f7-11e6-8412-005056a57341" (UID: "2a38c13d-f2f7-11e6-8412-005056a57341") with: Could not find attached VMDK "[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk". Timeout waiting for mount paths to be created.`

@kerneltime @BaluDontu @abrarshivani let me know if you need a setup to debug the issue.

**Comment by divyenpatel** [comment]
Logs from Master node.

`
grep "e2e-vmdk-1487105402969274636.vmdk" *
kube-controller-manager-master_kube-system_kube-controller-manager-744799c56305d439956522e69db52726e6b4b625256e9058d3c9c75ec9dd1c44.log:{"log":"I0214 20:50:06.155791       1 reconciler.go:213] Started AttachVolume for volume \"kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk\" to node \"node1\"\n","stream":"stderr","time":"2017-02-14T20:50:06.155941278Z"}
kube-controller-manager-master_kube-system_kube-controller-manager-744799c56305d439956522e69db52726e6b4b625256e9058d3c9c75ec9dd1c44.log:{"log":"I0214 20:50:08.102400       1 operation_executor.go:620] AttachVolume.Attach succeeded for volume \"kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk\" (spec.Name: \"vsphere-volume\") from node \"node1\".\n","stream":"stderr","time":"2017-02-14T20:50:08.102613311Z"}
kube-controller-manager-master_kube-system_kube-controller-manager-744799c56305d439956522e69db52726e6b4b625256e9058d3c9c75ec9dd1c44.log:{"log":"I0214 20:50:08.168081       1 node_status_updater.go:135] Updating status for node \"node1\" succeeded. patchBytes: \"{\\\"status\\\":{\\\"volumesAttached\\\":[{\\\"devicePath\\\":\\\"/dev/disk/by-id/wwn-0x6000c29c0d731ba342844f493622d9ca\\\",\\\"name\\\":\\\"kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk\\\"}]}}\" VolumesAttached: [{kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk /dev/disk/by-id/wwn-0x6000c29c0d731ba342844f493622d9ca}]\n","stream":"stderr","time":"2017-02-14T20:50:08.168174704Z"}
kube-controller-manager-master_kube-system_kube-controller-manager-744799c56305d439956522e69db52726e6b4b625256e9058d3c9c75ec9dd1c44.log:{"log":"I0214 20:56:42.030577       1 reconciler.go:178] Started DetachVolume for volume \"kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk\" from node \"node1\"\n","stream":"stderr","time":"2017-02-14T20:56:42.030672226Z"}
kube-controller-manager-master_kube-system_kube-controller-manager-744799c56305d439956522e69db52726e6b4b625256e9058d3c9c75ec9dd1c44.log:{"log":"I0214 20:56:42.034775       1 operation_executor.go:754] Verified volume is safe to detach for volume \"kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk\" (spec.Name: \"vsphere-volume\") from node \"node1\".\n","stream":"stderr","time":"2017-02-14T20:56:42.034939365Z"}
kube-controller-manager-master_kube-system_kube-controller-manager-744799c56305d439956522e69db52726e6b4b625256e9058d3c9c75ec9dd1c44.log:{"log":"I0214 20:56:43.702773       1 operation_executor.go:700] DetachVolume.Detach succeeded for volume \"kubernetes.io/vsphere-volume/[vsanDS] kubevols/e2e-vmdk-1487105402969274636.vmdk\" (spec.Name: \"vsphere-volume\") from node \"node1\".\n","stream":"stderr","time":"2017-02-14T20:56:43.703138147Z"}
`

**Comment by divyenpatel** [comment]
@abrarshivani as you suggested, deployed fresh testbed and observed the same issue - mount points not getting unmounted even after disk is detached from the node.

Here test creates two pods one after other, pointing to same volume.
(POD1 injects to content and POD2 reads and verifies the content)
Here is the test code : https://github.com/kubernetes/kubernetes/blob/master/test/e2e/volumes.go#L937 

not sure we should see multiple mount entries for same volume.

```
root@photon-zv1KbtvMG [ ~ ]# mount -l -t ext4
/dev/sda2 on / type ext4 (rw,noatime,noacl,data=ordered)
/dev/sda2 on /var/lib/kubelet type ext4 (rw,noatime,noacl,data=ordered)
/dev/sdb on /var/lib/kubelet/pods/6378d473-f336-11e6-a7cb-0050568e4783/volumes/kubernetes.io~vsphere-volume/vsphere-volume-0 type ext4 (rw,relatime,data=ordered)
/dev/sdb on /var/lib/kubelet/pods/6378d473-f336-11e6-a7cb-0050568e4783/volumes/kubernetes.io~vsphere-volume/vsphere-volume-0 type ext4 (rw,relatime,data=ordered)
root@photon-zv1KbtvMG [ ~ ]# 
```

Attaching log files from master and worker node

For the below logs
VMDK: kubevols/e2e-vmdk-1487132485517658526.vmdk

[master-kubelet-service.txt](https://github.com/vmware/kubernetes/files/776063/master-kubelet-service.txt)
[worker-kubelet-service.txt](https://github.com/vmware/kubernetes/files/776064/worker-kubelet-service.txt)

**Comment by pdhamdhere** [comment]
@abrarshivani @BaluDontu Is anyone of you looking into this? If you are already looking, please assign issue to yourself.

**Comment by BaluDontu** [comment]
I have tried executing the test multiple times with both guestbook.yaml and the YAML which @divyenpatel sent to me. Its working fine and I don't see any unmount issues as mentioned above.

**Comment by BaluDontu** [comment]
Closing the issue for now. @divyenpatel please reopen this, if you find this issue occuring again.
